#define IDX_DATA_NBC_TBL_DIM_NS    5
#define IDX_DATA_NBC_TBL_FACTOR_SZ    4
#define IDX_DATA_NBC_TBL_ENTRY_NS    25

static unsigned int _cam_data_entry_NBC_TBL_key0000[] = {0X0000007C, 0X00000000, 0X00800000, 0X000007EF, };
static unsigned int _cam_data_entry_NBC_TBL_key0001[] = {0X0000007C, 0X00000000, 0X00400000, 0X000007EF, };
static unsigned int _cam_data_entry_NBC_TBL_key0002[] = {0X0000007C, 0X00000000, 0X00800000, 0X000007F7, };
static unsigned int _cam_data_entry_NBC_TBL_key0003[] = {0X0000007C, 0X00000000, 0X00400000, 0X000007F7, };
static unsigned int _cam_data_entry_NBC_TBL_key0004[] = {0X00000001, 0X00000000, 0X00400040, 0X000007EF, };
static unsigned int _cam_data_entry_NBC_TBL_key0005[] = {0X00000001, 0X00000000, 0X00800040, 0X000007E9, };
static unsigned int _cam_data_entry_NBC_TBL_key0006[] = {0X00000001, 0X00000000, 0X01000040, 0X000007EF, };
static unsigned int _cam_data_entry_NBC_TBL_key0007[] = {0X00000001, 0X00000000, 0X00400040, 0X000007F7, };
static unsigned int _cam_data_entry_NBC_TBL_key0008[] = {0X00000001, 0X00000000, 0X00800040, 0X000007F1, };
static unsigned int _cam_data_entry_NBC_TBL_key0009[] = {0X00000001, 0X00000000, 0X01000040, 0X000007F7, };
static unsigned int _cam_data_entry_NBC_TBL_key0010[] = {0X00000002, 0X00000000, 0X00400080, 0X000007FF, };
static unsigned int _cam_data_entry_NBC_TBL_key0011[] = {0X00000002, 0X00000000, 0X01000080, 0X000007FF, };
static unsigned int _cam_data_entry_NBC_TBL_key0012[] = {0X00000000, 0X0000071C, 0XFFC1C000, 0X000007FF, };
static unsigned int _cam_data_entry_NBC_TBL_key0013[] = {0X00000000, 0X000038E0, 0XFFCE0000, 0X000007FF, };
static unsigned int _cam_data_entry_NBC_TBL_key0014[] = {0X00000000, 0X0000C000, 0XFFC00000, 0X000007FF, };
static unsigned int _cam_data_entry_NBC_TBL_key0015[] = {0X01C70000, 0X00000000, 0XFFC00700, 0X000007FF, };
static unsigned int _cam_data_entry_NBC_TBL_key0016[] = {0X0E380000, 0X00000000, 0XFFC03800, 0X000007FF, };
static unsigned int _cam_data_entry_NBC_TBL_key0017[] = {0XF0000000, 0X00000003, 0XFFC00000, 0X000007FF, };
static unsigned int _cam_data_entry_NBC_TBL_key0018[] = {0X00000300, 0X00000000, 0XFFC00000, 0X000007FF, };
static unsigned int _cam_data_entry_NBC_TBL_key0019[] = {0X00000C00, 0X00000000, 0XFFC00000, 0X000007FF, };
static unsigned int _cam_data_entry_NBC_TBL_key0020[] = {0X0000F000, 0X00000000, 0XFFC00000, 0X000007F9, };
static unsigned int _cam_data_entry_NBC_TBL_key0021[] = {0X0000F07C, 0X00000000, 0XFFC00000, 0X000007FA, };
static unsigned int _cam_data_entry_NBC_TBL_key0022[] = {0XF0000000, 0X0000C003, 0XFFC00000, 0X000007FA, };
static unsigned int _cam_data_entry_NBC_TBL_key0023[] = {0X00000001, 0X00000000, 0X00800040, 0X000007EA, };
static unsigned int _cam_data_entry_NBC_TBL_key0024[] = {0X00000001, 0X00000000, 0X00800040, 0X000007F2, };

static IDX_MASK_ENTRY _cam_data_entry_NBC_TBL[IDX_DATA_NBC_TBL_ENTRY_NS] =
{
    {(unsigned int*)&_cam_data_entry_NBC_TBL_key0000, 0, 0, 6, 0},
    {(unsigned int*)&_cam_data_entry_NBC_TBL_key0001, 0, 1, 6, 0},
    {(unsigned int*)&_cam_data_entry_NBC_TBL_key0002, 0, 2, 6, 0},
    {(unsigned int*)&_cam_data_entry_NBC_TBL_key0003, 0, 3, 6, 0},
    {(unsigned int*)&_cam_data_entry_NBC_TBL_key0004, 0, 4, 6, 0},
    {(unsigned int*)&_cam_data_entry_NBC_TBL_key0005, 0, 5, 6, 0},
    {(unsigned int*)&_cam_data_entry_NBC_TBL_key0006, 0, 6, 6, 0},
    {(unsigned int*)&_cam_data_entry_NBC_TBL_key0007, 0, 7, 6, 0},
    {(unsigned int*)&_cam_data_entry_NBC_TBL_key0008, 0, 8, 6, 0},
    {(unsigned int*)&_cam_data_entry_NBC_TBL_key0009, 0, 9, 6, 0},
    {(unsigned int*)&_cam_data_entry_NBC_TBL_key0010, 0, 10, 6, 0},
    {(unsigned int*)&_cam_data_entry_NBC_TBL_key0011, 0, 11, 6, 0},
    {(unsigned int*)&_cam_data_entry_NBC_TBL_key0012, 0, 12, 6, 0},
    {(unsigned int*)&_cam_data_entry_NBC_TBL_key0013, 0, 13, 6, 0},
    {(unsigned int*)&_cam_data_entry_NBC_TBL_key0014, 0, 14, 6, 0},
    {(unsigned int*)&_cam_data_entry_NBC_TBL_key0015, 0, 15, 6, 0},
    {(unsigned int*)&_cam_data_entry_NBC_TBL_key0016, 0, 16, 6, 0},
    {(unsigned int*)&_cam_data_entry_NBC_TBL_key0017, 0, 17, 6, 0},
    {(unsigned int*)&_cam_data_entry_NBC_TBL_key0018, 0, 18, 6, 0},
    {(unsigned int*)&_cam_data_entry_NBC_TBL_key0019, 0, 19, 6, 0},
    {(unsigned int*)&_cam_data_entry_NBC_TBL_key0020, 0, 20, 6, 0},
    {(unsigned int*)&_cam_data_entry_NBC_TBL_key0021, 6, 21, 0, 0},
    {(unsigned int*)&_cam_data_entry_NBC_TBL_key0022, 6, 22, 0, 0},
    {(unsigned int*)&_cam_data_entry_NBC_TBL_key0023, 0, 23, 6, 0},
    {(unsigned int*)&_cam_data_entry_NBC_TBL_key0024, 0, 24, 6, 0},
};

static unsigned short _cam_data_dims_NBC_TBL[] = 
{
    EDim_IspProfile,
    EDim_SensorMode,
    EDim_Flash,
    EDim_FaceDetection,
    EDim_LV,
};

static unsigned short _cam_data_expand_NBC_TBL[] = 
{1, 0, 0};

const IDX_MASK_T cam_data_NBC_TBL =
{
    {IDX_ALGO_MASK, IDX_DATA_NBC_TBL_DIM_NS, (unsigned short*)&_cam_data_dims_NBC_TBL, (unsigned short*)&_cam_data_expand_NBC_TBL},
    {IDX_DATA_NBC_TBL_ENTRY_NS, IDX_DATA_NBC_TBL_FACTOR_SZ, (IDX_MASK_ENTRY*)&_cam_data_entry_NBC_TBL}
};