/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 */
/* MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

/********************************************************************************************
 *     LEGAL DISCLAIMER
 *
 *     (Header of MediaTek Software/Firmware Release or Documentation)
 *
 *     BY OPENING OR USING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 *     THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE") RECEIVED
 *     FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON AN "AS-IS" BASIS
 *     ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED,
 *     INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR
 *     A PARTICULAR PURPOSE OR NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY
 *     WHATSOEVER WITH RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 *     INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK
 *     ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
 *     NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S SPECIFICATION
 *     OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
 *
 *     BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE LIABILITY WITH
 *     RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION,
TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE
 *     FEES OR SERVICE CHARGE PAID BY BUYER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 *     THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE WITH THE LAWS
 *     OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF LAWS PRINCIPLES.
 ************************************************************************************************/
#ifndef _CFG_ISP_TUNING_IDX_CAPTURE_H_
#define _CFG_ISP_TUNING_IDX_CAPTURE_H_


#include <mtkcam/metadata/client/mtk_metadata_tag.h>

#define CAPTURE_SCENE_MODE_CONFIG(sensor, scene)\
    IDX_MODE_Capture(sensor, scene, eIDX_ISO_100)\
    IdxSet<EIspProfile_Capture, sensor, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_100>::idx;\
    IDX_MODE_Capture(sensor, scene, eIDX_ISO_200)\
    IdxSet<EIspProfile_Capture, sensor, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_200>::idx;\
    IDX_MODE_Capture(sensor, scene, eIDX_ISO_400)\
    IdxSet<EIspProfile_Capture, sensor, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_400>::idx;\
    IDX_MODE_Capture(sensor, scene, eIDX_ISO_800)\
    IdxSet<EIspProfile_Capture, sensor, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_800>::idx;\
    IDX_MODE_Capture(sensor, scene, eIDX_ISO_1200)\
    IdxSet<EIspProfile_Capture, sensor, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1200>::idx;\
    IDX_MODE_Capture(sensor, scene, eIDX_ISO_1600)\
    IdxSet<EIspProfile_Capture, sensor, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1600>::idx;\
    IDX_MODE_Capture(sensor, scene, eIDX_ISO_2000)\
    IdxSet<EIspProfile_Capture, sensor, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2000>::idx;\
    IDX_MODE_Capture(sensor, scene, eIDX_ISO_2400)\
    IdxSet<EIspProfile_Capture, sensor, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2400>::idx;\
    IDX_MODE_Capture(sensor, scene, eIDX_ISO_2800)\
    IdxSet<EIspProfile_Capture, sensor, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2800>::idx;\
    IDX_MODE_Capture(sensor, scene, eIDX_ISO_3200)\
    IdxSet<EIspProfile_Capture, sensor, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_3200>::idx;\

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Capture> <Sensor Mode: Preview>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_UNSUPPORTED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Capture( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_100 )
IDX_SET( DBS:100, OBC:20, BPC:100, NR1:100, UDM:100, GGM:0, ANR:100, ANR2:100, CCR:0, BOK:0, EE:100, NR3D:0, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Capture( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_200 )
IDX_SET( DBS:101, OBC:20, BPC:101, NR1:101, UDM:101, GGM:0, ANR:101, ANR2:101, CCR:1, BOK:0, EE:101, NR3D:0, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Capture( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_400 )
IDX_SET( DBS:102, OBC:20, BPC:102, NR1:102, UDM:102, GGM:0, ANR:102, ANR2:102, CCR:2, BOK:1, EE:102, NR3D:0, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Capture( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_800 )
IDX_SET( DBS:103, OBC:21, BPC:103, NR1:103, UDM:103, GGM:0, ANR:103, ANR2:103, CCR:3, BOK:1, EE:103, NR3D:0, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Capture( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1200 )
IDX_SET( DBS:104, OBC:21, BPC:104, NR1:104, UDM:104, GGM:0, ANR:104, ANR2:104, CCR:4, BOK:2, EE:104, NR3D:0, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Capture( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1600 )
IDX_SET( DBS:105, OBC:21, BPC:105, NR1:105, UDM:105, GGM:0, ANR:105, ANR2:105, CCR:5, BOK:2, EE:105, NR3D:0, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Capture( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2000 )
IDX_SET( DBS:106, OBC:21, BPC:106, NR1:106, UDM:106, GGM:0, ANR:106, ANR2:106, CCR:6, BOK:3, EE:106, NR3D:0, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Capture( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2400 )
IDX_SET( DBS:107, OBC:21, BPC:107, NR1:107, UDM:107, GGM:0, ANR:107, ANR2:107, CCR:7, BOK:3, EE:107, NR3D:0, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Capture( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2800 )
IDX_SET( DBS:108, OBC:21, BPC:108, NR1:108, UDM:108, GGM:0, ANR:108, ANR2:108, CCR:8, BOK:4, EE:108, NR3D:0, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Capture( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_3200 )
IDX_SET( DBS:109, OBC:21, BPC:109, NR1:109, UDM:109, GGM:0, ANR:109, ANR2:109, CCR:9, BOK:4, EE:109, NR3D:0, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_NORMAL)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_ACTION)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_NIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_THEATRE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_BEACH)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_SNOW)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_SUNSET)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_FIREWORKS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_SPORTS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_PARTY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_HDR)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Capture> <Sensor Mode: Capture>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_UNSUPPORTED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Capture( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_100 )
IDX_SET( DBS:110, OBC:22, BPC:110, NR1:110, UDM:110, GGM:0, ANR:110, ANR2:110, CCR:0, BOK:5, EE:110, NR3D:0, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Capture( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_200 )
IDX_SET( DBS:111, OBC:22, BPC:111, NR1:111, UDM:111, GGM:0, ANR:111, ANR2:111, CCR:1, BOK:5, EE:111, NR3D:0, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Capture( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_400 )
IDX_SET( DBS:112, OBC:22, BPC:112, NR1:112, UDM:112, GGM:0, ANR:112, ANR2:112, CCR:2, BOK:6, EE:112, NR3D:0, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Capture( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_800 )
IDX_SET( DBS:113, OBC:23, BPC:113, NR1:113, UDM:113, GGM:0, ANR:113, ANR2:113, CCR:3, BOK:6, EE:113, NR3D:0, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Capture( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1200 )
IDX_SET( DBS:114, OBC:23, BPC:114, NR1:114, UDM:114, GGM:0, ANR:114, ANR2:114, CCR:4, BOK:7, EE:114, NR3D:0, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Capture( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1600 )
IDX_SET( DBS:115, OBC:23, BPC:115, NR1:115, UDM:115, GGM:0, ANR:115, ANR2:115, CCR:5, BOK:7, EE:115, NR3D:0, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Capture( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2000 )
IDX_SET( DBS:116, OBC:23, BPC:116, NR1:116, UDM:116, GGM:0, ANR:116, ANR2:116, CCR:6, BOK:8, EE:116, NR3D:0, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Capture( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2400 )
IDX_SET( DBS:117, OBC:23, BPC:117, NR1:117, UDM:117, GGM:0, ANR:117, ANR2:117, CCR:7, BOK:8, EE:117, NR3D:0, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Capture( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2800 )
IDX_SET( DBS:118, OBC:23, BPC:118, NR1:118, UDM:118, GGM:0, ANR:118, ANR2:118, CCR:8, BOK:9, EE:118, NR3D:0, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Capture( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_3200 )
IDX_SET( DBS:119, OBC:23, BPC:119, NR1:119, UDM:119, GGM:0, ANR:119, ANR2:119, CCR:9, BOK:9, EE:119, NR3D:0, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_NORMAL)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_ACTION)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_NIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_THEATRE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_BEACH)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_SNOW)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_SUNSET)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_FIREWORKS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_SPORTS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_PARTY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_HDR)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_BARCODE)


//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Capture> <Sensor Mode: Video>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_UNSUPPORTED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Capture( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_100 )
IDX_SET( DBS:120, OBC:24, BPC:120, NR1:120, UDM:120, GGM:0, ANR:120, ANR2:120, CCR:0, BOK:10, EE:120, NR3D:0, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Capture( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_200 )
IDX_SET( DBS:121, OBC:24, BPC:121, NR1:121, UDM:121, GGM:0, ANR:121, ANR2:121, CCR:1, BOK:10, EE:121, NR3D:0, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Capture( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_400 )
IDX_SET( DBS:122, OBC:24, BPC:122, NR1:122, UDM:122, GGM:0, ANR:122, ANR2:122, CCR:2, BOK:11, EE:122, NR3D:0, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Capture( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_800 )
IDX_SET( DBS:123, OBC:25, BPC:123, NR1:123, UDM:123, GGM:0, ANR:123, ANR2:123, CCR:3, BOK:11, EE:123, NR3D:0, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Capture( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1200 )
IDX_SET( DBS:124, OBC:25, BPC:124, NR1:124, UDM:124, GGM:0, ANR:124, ANR2:124, CCR:4, BOK:12, EE:124, NR3D:0, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Capture( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1600 )
IDX_SET( DBS:125, OBC:25, BPC:125, NR1:125, UDM:125, GGM:0, ANR:125, ANR2:125, CCR:5, BOK:12, EE:125, NR3D:0, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Capture( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2000 )
IDX_SET( DBS:126, OBC:25, BPC:126, NR1:126, UDM:126, GGM:0, ANR:126, ANR2:126, CCR:6, BOK:13, EE:126, NR3D:0, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Capture( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2400 )
IDX_SET( DBS:127, OBC:25, BPC:127, NR1:127, UDM:127, GGM:0, ANR:127, ANR2:127, CCR:7, BOK:13, EE:127, NR3D:0, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Capture( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2800 )
IDX_SET( DBS:128, OBC:25, BPC:128, NR1:128, UDM:128, GGM:0, ANR:128, ANR2:128, CCR:8, BOK:14, EE:128, NR3D:0, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Capture( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_3200 )
IDX_SET( DBS:129, OBC:25, BPC:129, NR1:129, UDM:129, GGM:0, ANR:129, ANR2:129, CCR:9, BOK:14, EE:129, NR3D:0, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_NORMAL)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_ACTION)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_NIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_THEATRE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_BEACH)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_SNOW)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_SUNSET)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_FIREWORKS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_SPORTS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_PARTY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_HDR)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_BARCODE)


//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Capture> <Sensor Mode: SlimVideo1>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_UNSUPPORTED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Capture( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_100 )
IDX_SET( DBS:130, OBC:26, BPC:130, NR1:130, UDM:130, GGM:0, ANR:130, ANR2:130, CCR:0, BOK:15, EE:130, NR3D:0, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Capture( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_200 )
IDX_SET( DBS:131, OBC:26, BPC:131, NR1:131, UDM:131, GGM:0, ANR:131, ANR2:131, CCR:1, BOK:15, EE:131, NR3D:0, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Capture( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_400 )
IDX_SET( DBS:132, OBC:26, BPC:132, NR1:132, UDM:132, GGM:0, ANR:132, ANR2:132, CCR:2, BOK:16, EE:132, NR3D:0, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Capture( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_800 )
IDX_SET( DBS:133, OBC:27, BPC:133, NR1:133, UDM:133, GGM:0, ANR:133, ANR2:133, CCR:3, BOK:16, EE:133, NR3D:0, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Capture( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1200 )
IDX_SET( DBS:134, OBC:27, BPC:134, NR1:134, UDM:134, GGM:0, ANR:134, ANR2:134, CCR:4, BOK:17, EE:134, NR3D:0, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Capture( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1600 )
IDX_SET( DBS:135, OBC:27, BPC:135, NR1:135, UDM:135, GGM:0, ANR:135, ANR2:135, CCR:5, BOK:17, EE:135, NR3D:0, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Capture( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2000 )
IDX_SET( DBS:136, OBC:27, BPC:136, NR1:136, UDM:136, GGM:0, ANR:136, ANR2:136, CCR:6, BOK:18, EE:136, NR3D:0, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Capture( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2400 )
IDX_SET( DBS:137, OBC:27, BPC:137, NR1:137, UDM:137, GGM:0, ANR:137, ANR2:137, CCR:7, BOK:18, EE:137, NR3D:0, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Capture( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2800 )
IDX_SET( DBS:138, OBC:27, BPC:138, NR1:138, UDM:138, GGM:0, ANR:138, ANR2:138, CCR:8, BOK:19, EE:138, NR3D:0, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Capture( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_3200 )
IDX_SET( DBS:139, OBC:27, BPC:139, NR1:139, UDM:139, GGM:0, ANR:139, ANR2:139, CCR:9, BOK:19, EE:139, NR3D:0, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_NORMAL)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_ACTION)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_NIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_THEATRE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_BEACH)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_SNOW)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_SUNSET)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_FIREWORKS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_SPORTS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_PARTY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_HDR)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Capture> <Sensor Mode: SlimVideo2>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_UNSUPPORTED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Capture( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_100 )
IDX_SET( DBS:140, OBC:28, BPC:140, NR1:140, UDM:140, GGM:0, ANR:140, ANR2:140, CCR:0, BOK:20, EE:140, NR3D:0, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Capture( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_200 )
IDX_SET( DBS:141, OBC:28, BPC:141, NR1:141, UDM:141, GGM:0, ANR:141, ANR2:141, CCR:1, BOK:20, EE:141, NR3D:0, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Capture( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_400 )
IDX_SET( DBS:142, OBC:28, BPC:142, NR1:142, UDM:142, GGM:0, ANR:142, ANR2:142, CCR:2, BOK:21, EE:142, NR3D:0, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Capture( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_800 )
IDX_SET( DBS:143, OBC:29, BPC:143, NR1:143, UDM:143, GGM:0, ANR:143, ANR2:143, CCR:3, BOK:21, EE:143, NR3D:0, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Capture( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1200 )
IDX_SET( DBS:144, OBC:29, BPC:144, NR1:144, UDM:144, GGM:0, ANR:144, ANR2:144, CCR:4, BOK:22, EE:144, NR3D:0, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Capture( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1600 )
IDX_SET( DBS:145, OBC:29, BPC:145, NR1:145, UDM:145, GGM:0, ANR:145, ANR2:145, CCR:5, BOK:22, EE:145, NR3D:0, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Capture( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2000 )
IDX_SET( DBS:146, OBC:29, BPC:146, NR1:146, UDM:146, GGM:0, ANR:146, ANR2:146, CCR:6, BOK:23, EE:146, NR3D:0, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Capture( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2400 )
IDX_SET( DBS:147, OBC:29, BPC:147, NR1:147, UDM:147, GGM:0, ANR:147, ANR2:147, CCR:7, BOK:23, EE:147, NR3D:0, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Capture( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2800 )
IDX_SET( DBS:148, OBC:29, BPC:148, NR1:148, UDM:148, GGM:0, ANR:148, ANR2:148, CCR:8, BOK:24, EE:148, NR3D:0, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Capture( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_3200 )
IDX_SET( DBS:149, OBC:29, BPC:149, NR1:149, UDM:149, GGM:0, ANR:149, ANR2:149, CCR:9, BOK:24, EE:149, NR3D:0, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_NORMAL)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_ACTION)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_NIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_THEATRE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_BEACH)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_SNOW)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_SUNSET)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_FIREWORKS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_SPORTS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_PARTY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_HDR)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Capture> <Sensor Mode: Custom1>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_UNSUPPORTED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Capture( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_100 )
IDX_SET( DBS:300, OBC:60, BPC:300, NR1:280, UDM:300, GGM:0, ANR:360, ANR2:360, CCR:0, BOK:25, EE:320, NR3D:0, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Capture( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_200 )
IDX_SET( DBS:301, OBC:60, BPC:301, NR1:281, UDM:301, GGM:0, ANR:361, ANR2:361, CCR:1, BOK:25, EE:321, NR3D:0, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Capture( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_400 )
IDX_SET( DBS:302, OBC:60, BPC:302, NR1:282, UDM:302, GGM:0, ANR:362, ANR2:362, CCR:2, BOK:26, EE:322, NR3D:0, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Capture( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_800 )
IDX_SET( DBS:303, OBC:61, BPC:303, NR1:283, UDM:303, GGM:0, ANR:363, ANR2:363, CCR:3, BOK:26, EE:323, NR3D:0, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Capture( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1200 )
IDX_SET( DBS:304, OBC:61, BPC:304, NR1:284, UDM:304, GGM:0, ANR:364, ANR2:364, CCR:4, BOK:27, EE:324, NR3D:0, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Capture( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1600 )
IDX_SET( DBS:305, OBC:61, BPC:305, NR1:285, UDM:305, GGM:0, ANR:365, ANR2:365, CCR:5, BOK:27, EE:325, NR3D:0, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Capture( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2000 )
IDX_SET( DBS:306, OBC:61, BPC:306, NR1:286, UDM:306, GGM:0, ANR:366, ANR2:366, CCR:6, BOK:28, EE:326, NR3D:0, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Capture( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2400 )
IDX_SET( DBS:307, OBC:61, BPC:307, NR1:287, UDM:307, GGM:0, ANR:367, ANR2:367, CCR:7, BOK:28, EE:327, NR3D:0, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Capture( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2800 )
IDX_SET( DBS:308, OBC:61, BPC:308, NR1:288, UDM:308, GGM:0, ANR:368, ANR2:368, CCR:8, BOK:29, EE:328, NR3D:0, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Capture( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_3200 )
IDX_SET( DBS:309, OBC:61, BPC:309, NR1:289, UDM:309, GGM:0, ANR:369, ANR2:369, CCR:9, BOK:29, EE:329, NR3D:0, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_NORMAL)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_ACTION)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_NIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_THEATRE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_BEACH)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_SNOW)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_SUNSET)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_FIREWORKS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_SPORTS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_PARTY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_HDR)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Capture> <Sensor Mode: Custom2>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_UNSUPPORTED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Capture( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_100 )
IDX_SET( DBS:310, OBC:62, BPC:310, NR1:290, UDM:310, GGM:0, ANR:370, ANR2:370, CCR:0, BOK:30, EE:330, NR3D:0, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Capture( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_200 )
IDX_SET( DBS:311, OBC:62, BPC:311, NR1:291, UDM:311, GGM:0, ANR:371, ANR2:371, CCR:1, BOK:30, EE:331, NR3D:0, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Capture( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_400 )
IDX_SET( DBS:312, OBC:62, BPC:312, NR1:292, UDM:312, GGM:0, ANR:372, ANR2:372, CCR:2, BOK:31, EE:332, NR3D:0, MFB:0, LCE:0);
// ISO 8004
IDX_MODE_Capture( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_800 )
IDX_SET( DBS:313, OBC:63, BPC:313, NR1:293, UDM:313, GGM:0, ANR:373, ANR2:373, CCR:3, BOK:31, EE:333, NR3D:0, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Capture( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1200 )
IDX_SET( DBS:314, OBC:63, BPC:314, NR1:294, UDM:314, GGM:0, ANR:374, ANR2:374, CCR:4, BOK:32, EE:334, NR3D:0, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Capture( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1600 )
IDX_SET( DBS:315, OBC:63, BPC:315, NR1:295, UDM:315, GGM:0, ANR:375, ANR2:375, CCR:5, BOK:32, EE:335, NR3D:0, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Capture( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2000 )
IDX_SET( DBS:316, OBC:63, BPC:316, NR1:296, UDM:316, GGM:0, ANR:376, ANR2:376, CCR:6, BOK:33, EE:336, NR3D:0, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Capture( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2400 )
IDX_SET( DBS:317, OBC:63, BPC:317, NR1:297, UDM:317, GGM:0, ANR:377, ANR2:377, CCR:7, BOK:33, EE:337, NR3D:0, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Capture( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2800 )
IDX_SET( DBS:318, OBC:63, BPC:318, NR1:298, UDM:318, GGM:0, ANR:378, ANR2:378, CCR:8, BOK:34, EE:338, NR3D:0, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Capture( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_3200 )
IDX_SET( DBS:319, OBC:63, BPC:319, NR1:299, UDM:319, GGM:0, ANR:379, ANR2:379, CCR:9, BOK:34, EE:339, NR3D:0, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_NORMAL)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_ACTION)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_NIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_THEATRE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_BEACH)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_SNOW)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_SUNSET)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_FIREWORKS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_SPORTS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_PARTY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_HDR)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Capture> <Sensor Mode: Custom3>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_UNSUPPORTED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Capture( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_100 )
IDX_SET( DBS:320, OBC:64, BPC:320, NR1:300, UDM:320, GGM:0, ANR:380, ANR2:380, CCR:0, BOK:35, EE:340, NR3D:0, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Capture( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_200 )
IDX_SET( DBS:321, OBC:64, BPC:321, NR1:301, UDM:321, GGM:0, ANR:381, ANR2:381, CCR:1, BOK:35, EE:341, NR3D:0, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Capture( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_400 )
IDX_SET( DBS:322, OBC:64, BPC:322, NR1:302, UDM:322, GGM:0, ANR:382, ANR2:382, CCR:2, BOK:36, EE:342, NR3D:0, MFB:0, LCE:0);
// ISO 8004
IDX_MODE_Capture( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_800 )
IDX_SET( DBS:323, OBC:65, BPC:323, NR1:303, UDM:323, GGM:0, ANR:383, ANR2:383, CCR:3, BOK:36, EE:343, NR3D:0, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Capture( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1200 )
IDX_SET( DBS:324, OBC:65, BPC:324, NR1:304, UDM:324, GGM:0, ANR:384, ANR2:384, CCR:4, BOK:37, EE:344, NR3D:0, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Capture( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1600 )
IDX_SET( DBS:325, OBC:65, BPC:325, NR1:305, UDM:325, GGM:0, ANR:385, ANR2:385, CCR:5, BOK:37, EE:345, NR3D:0, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Capture( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2000 )
IDX_SET( DBS:326, OBC:65, BPC:326, NR1:306, UDM:326, GGM:0, ANR:386, ANR2:386, CCR:6, BOK:38, EE:346, NR3D:0, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Capture( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2400 )
IDX_SET( DBS:327, OBC:65, BPC:327, NR1:307, UDM:327, GGM:0, ANR:387, ANR2:387, CCR:7, BOK:38, EE:347, NR3D:0, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Capture( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2800 )
IDX_SET( DBS:328, OBC:65, BPC:328, NR1:308, UDM:328, GGM:0, ANR:388, ANR2:388, CCR:8, BOK:39, EE:348, NR3D:0, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Capture( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_3200 )
IDX_SET( DBS:329, OBC:65, BPC:329, NR1:309, UDM:329, GGM:0, ANR:389, ANR2:389, CCR:9, BOK:39, EE:349, NR3D:0, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_NORMAL)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_ACTION)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_NIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_THEATRE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_BEACH)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_SNOW)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_SUNSET)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_FIREWORKS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_SPORTS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_PARTY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_HDR)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Capture> <Sensor Mode: Custom4>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_UNSUPPORTED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Capture( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_100 )
IDX_SET( DBS:330, OBC:66, BPC:330, NR1:310, UDM:330, GGM:0, ANR:390, ANR2:390, CCR:0, BOK:40, EE:350, NR3D:0, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Capture( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_200 )
IDX_SET( DBS:331, OBC:66, BPC:331, NR1:311, UDM:331, GGM:0, ANR:391, ANR2:391, CCR:1, BOK:40, EE:351, NR3D:0, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Capture( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_400 )
IDX_SET( DBS:332, OBC:66, BPC:332, NR1:312, UDM:332, GGM:0, ANR:392, ANR2:392, CCR:2, BOK:41, EE:352, NR3D:0, MFB:0, LCE:0);
// ISO 8004
IDX_MODE_Capture( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_800 )
IDX_SET( DBS:333, OBC:67, BPC:333, NR1:313, UDM:333, GGM:0, ANR:393, ANR2:393, CCR:3, BOK:41, EE:353, NR3D:0, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Capture( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1200 )
IDX_SET( DBS:334, OBC:67, BPC:334, NR1:314, UDM:334, GGM:0, ANR:394, ANR2:394, CCR:4, BOK:42, EE:354, NR3D:0, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Capture( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1600 )
IDX_SET( DBS:335, OBC:67, BPC:335, NR1:315, UDM:335, GGM:0, ANR:395, ANR2:395, CCR:5, BOK:42, EE:355, NR3D:0, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Capture( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2000 )
IDX_SET( DBS:336, OBC:67, BPC:336, NR1:316, UDM:336, GGM:0, ANR:396, ANR2:396, CCR:6, BOK:43, EE:356, NR3D:0, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Capture( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2400 )
IDX_SET( DBS:337, OBC:67, BPC:337, NR1:317, UDM:337, GGM:0, ANR:397, ANR2:397, CCR:7, BOK:43, EE:357, NR3D:0, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Capture( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2800 )
IDX_SET( DBS:338, OBC:67, BPC:338, NR1:318, UDM:338, GGM:0, ANR:398, ANR2:398, CCR:8, BOK:44, EE:358, NR3D:0, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Capture( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_3200 )
IDX_SET( DBS:339, OBC:67, BPC:339, NR1:319, UDM:339, GGM:0, ANR:399, ANR2:399, CCR:9, BOK:44, EE:359, NR3D:0, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_NORMAL)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_ACTION)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_NIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_THEATRE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_BEACH)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_SNOW)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_SUNSET)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_FIREWORKS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_SPORTS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_PARTY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_HDR)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Capture> <Sensor Mode: Custom5>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_UNSUPPORTED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Capture( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_100 )
IDX_SET( DBS:340, OBC:68, BPC:340, NR1:320, UDM:340, GGM:0, ANR:400, ANR2:400, CCR:0, BOK:45, EE:360, NR3D:0, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Capture( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_200 )
IDX_SET( DBS:341, OBC:68, BPC:341, NR1:321, UDM:341, GGM:0, ANR:401, ANR2:401, CCR:1, BOK:45, EE:361, NR3D:0, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Capture( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_400 )
IDX_SET( DBS:342, OBC:68, BPC:342, NR1:322, UDM:342, GGM:0, ANR:402, ANR2:402, CCR:2, BOK:46, EE:362, NR3D:0, MFB:0, LCE:0);
// ISO 8004
IDX_MODE_Capture( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_800 )
IDX_SET( DBS:343, OBC:69, BPC:343, NR1:323, UDM:343, GGM:0, ANR:403, ANR2:403, CCR:3, BOK:46, EE:363, NR3D:0, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Capture( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1200 )
IDX_SET( DBS:344, OBC:69, BPC:344, NR1:324, UDM:344, GGM:0, ANR:404, ANR2:404, CCR:4, BOK:47, EE:364, NR3D:0, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Capture( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1600 )
IDX_SET( DBS:345, OBC:69, BPC:345, NR1:325, UDM:345, GGM:0, ANR:405, ANR2:405, CCR:5, BOK:47, EE:365, NR3D:0, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Capture( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2000 )
IDX_SET( DBS:346, OBC:69, BPC:346, NR1:326, UDM:346, GGM:0, ANR:406, ANR2:406, CCR:6, BOK:48, EE:366, NR3D:0, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Capture( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2400 )
IDX_SET( DBS:347, OBC:69, BPC:347, NR1:327, UDM:347, GGM:0, ANR:407, ANR2:407, CCR:7, BOK:48, EE:367, NR3D:0, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Capture( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2800 )
IDX_SET( DBS:348, OBC:69, BPC:348, NR1:328, UDM:348, GGM:0, ANR:408, ANR2:408, CCR:8, BOK:49, EE:368, NR3D:0, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Capture( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_3200 )
IDX_SET( DBS:349, OBC:69, BPC:349, NR1:329, UDM:349, GGM:0, ANR:409, ANR2:409, CCR:9, BOK:49, EE:369, NR3D:0, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_NORMAL)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_ACTION)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_NIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_THEATRE)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_BEACH)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_SNOW)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_SUNSET)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_FIREWORKS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_SPORTS)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_PARTY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_HDR)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
CAPTURE_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_BARCODE)


#endif //  _CFG_ISP_TUNING_IDX_CAPTURE_H_

