const ISP_NVRAM_BPC_BPC_T BPC_BPC_%04d = {
    .con       ={.bits ={.BPC_BPC_EN=1, .rsv_1=0, .BPC_BPC_LUT_EN=0, .BPC_BPC_TABLE_END_MODE=1, .rsv_6=0, .BPC_BPC_AVG_MODE=0, .rsv_9=0, .BPC_BPC_DTC_MODE=0, .BPC_BPC_CS_MODE=2, .BPC_BPC_CRC_MODE=0, .BPC_BPC_EXC=0, .BPC_BPC_BLD_MODE=0, .BPC_LE_INV_CTL=0, .BPC_BPC_AUX_MAP_EN=0, .BPC_BPC_AUX_MAP_OR_EN=0, .rsv_26=0, .BPC_BNR_EDGE=15}},
    .bld       ={.bits ={.BPC_BPC_BLD0=0, .rsv_7=0, .BPC_BPC_BLD1=64, .rsv_15=0, .BPC_BPC_BLD_SP=5, .rsv_24=0}},
    .th1       ={.bits ={.BPC_BPC_TH_LWB=50, .rsv_15=0, .BPC_BPC_TH_Y=151, .rsv_31=0}},
    .th2       ={.bits ={.BPC_BPC_TH_XB=568, .rsv_15=0, .BPC_BPC_TH_UPB=500, .rsv_31=0}},
    .th3       ={.bits ={.BPC_BPC_DK_TH_XB=1600, .rsv_15=0, .BPC_BPC_TH_XA=301, .rsv_31=0}},
    .th4       ={.bits ={.BPC_BPC_DK_TH_XA=1000, .rsv_15=0}},
    .th5       ={.bits ={.BPC_BPC_TH_SLA=15, .BPC_BPC_TH_SLB=6, .rsv_8=0}},
    .th6       ={.bits ={.BPC_BPC_DK_TH_SLA=6, .BPC_BPC_DK_TH_SLB=3, .rsv_8=0}},
    .dtc       ={.bits ={.BPC_BPC_RNG=1, .BPC_BPC_CS_RNG=1, .rsv_7=0, .BPC_BPC_CT_LV=0, .rsv_12=0, .BPC_BPC_TH_MUL=10, .rsv_20=0, .BPC_BPC_NO_LV=3, .rsv_27=0}},
    .cor       ={.bits ={.BPC_BPC_DIR_MAX=25, .BPC_BPC_DIR_TH=5, .rsv_16=0, .BPC_BPC_DIR_TH2=5}},
    .rank      ={.bits ={.BPC_BPC_RANK_IDXB=1, .rsv_3=0, .BPC_BPC_RANK_IDXR=1, .rsv_7=0, .BPC_BPC_RANK_IDXG=1, .rsv_11=0, .BPC_BPC_BLD_LWB=200, .rsv_24=0}},
    .th1_c     ={.bits ={.BPC_BPC_C_TH_LWB=90, .rsv_15=0, .BPC_BPC_C_TH_Y=213, .rsv_31=0}},
    .th2_c     ={.bits ={.BPC_BPC_C_TH_XA=160, .rsv_15=0, .BPC_BPC_C_TH_XB=700, .rsv_31=0}},
    .th3_c     ={.bits ={.BPC_BPC_C_TH_SLA=12, .BPC_BPC_C_TH_SLB=3, .BPC_BPC_C_TH_UPB=500, .rsv_23=0}},
    .ll        ={.bits ={.BPC_BPC_LL_LWB=0, .BPC_BPC_LL_LSP=0, .rsv_17=0}},
    //.number    ={.bits ={.BPC_BPC_NUMBER=0, .rsv_13=0}},
    .zhdr_con  ={.bits ={.BPC_ZHDR_EN=0, .rsv_1=0, .BPC_ZHDR_GLE_FIRST=0, .rsv_5=0, .BPC_ZHDR_RLE_FIRST=0, .rsv_9=0, .BPC_ZHDR_BLE_FIRST=0, .rsv_13=0, .BPC_ZHDR_OSC_COUNT=5, .BPC_ZHDR_OSC_TH=510}},
    .pseudo    ={.bits ={.BPC_ZHDR_CLAMP_EN=1, .rsv_1=0, .BPC_ZHDR_OUT_SEL_EN=0, .rsv_9=0, .BPC_BPC_OC_MEAN_EN=0, .rsv_17=0, .BPC_PDC_GAIN_MODE_EN=0, .rsv_21=0}},
};
