/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 */
/* MediaTek Inc. (C) 2018. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

/********************************************************************************************
*     LEGAL DISCLAIMER
*
*     (Header of MediaTek Software/Firmware Release or Documentation)
*
*     BY OPENING OR USING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*     THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE") RECEIVED
*     FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON AN "AS-IS" BASIS
*     ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED,
*     INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR
*     A PARTICULAR PURPOSE OR NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY
*     WHATSOEVER WITH RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
*     INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK
*     ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*     NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S SPECIFICATION
*     OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*     BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE LIABILITY WITH
*     RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION,
*     TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE
*     FEES OR SERVICE CHARGE PAID BY BUYER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*     THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE WITH THE LAWS
*     OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF LAWS PRINCIPLES.
************************************************************************************************/
#ifndef CAMERA_CUSTOM_STEREO_TUNING_H_
#define CAMERA_CUSTOM_STEREO_TUNING_H_
const char *DEFAULT_STEREO_TUNING =
"{"
    "\"HW_FE\": [{"
            "\"Parameters\": {"
                "\"BlockSize\": 8"
            "},"
            "\"Values\": {"
                "\"mFEMODE\": 2,"
                "\"mFEPARAM\": 4,"
                "\"mFEFLT_EN\": 1,"
                "\"mFETH_G\": 1,"
                "\"mFETH_C\": 0,"
                "\"mFEDSCR_SBIT\": 3,"
                "\"mFEXIDX\": 0,"
                "\"mFEYIDX\": 0,"
                "\"mFESTART_X\": 0,"
                "\"mFESTART_Y\": 0,"
                "\"mFEIN_HT\": 0,"
                "\"mFEIN_WD\": 0"
            "}"
        "}, {"
            "\"Parameters\": {"
                "\"BlockSize\": 16"
            "},"
            "\"Values\": {"
                "\"mFEMODE\": 1,"
                "\"mFEPARAM\": 4,"
                "\"mFEFLT_EN\": 1,"
                "\"mFETH_G\": 1,"
                "\"mFETH_C\": 0,"
                "\"mFEDSCR_SBIT\": 3,"
                "\"mFEXIDX\": 0,"
                "\"mFEYIDX\": 0,"
                "\"mFESTART_X\": 0,"
                "\"mFESTART_Y\": 0,"
                "\"mFEIN_HT\": 0,"
                "\"mFEIN_WD\": 0"
            "}"
        "}],"
    "\"HW_FM\": [{"
            "\"Parameters\": {"
                "\"Direction\": \"Right to Left\""
            "},"
            "\"Values\": {"
                "\"mFMOFFSET_X\": 20,"
                "\"mFMOFFSET_Y\": 16,"
                "\"mFMSR_TYPE\": 0,"
                "\"mFMMIN_RATIO\": 90,"
                "\"mFMSAD_TH\": 1023,"
                "\"mFMRES_TH\": 0"
            "}"
        "}, {"
            "\"Parameters\": {"
                "\"Direction\": \"Left to Right\""
            "},"
            "\"Values\": {"
                "\"mFMOFFSET_X\": 12,"
                "\"mFMOFFSET_Y\": 16,"
                "\"mFMSR_TYPE\": 0,"
                "\"mFMMIN_RATIO\": 90,"
                "\"mFMSAD_TH\": 1023,"
                "\"mFMRES_TH\": 0"
            "}"
        "}],"
    "\"HW_DPE_DVS_CTRL\": [{"
        "\"Parameters\": {"
            "\"Scenario\": \"Preview\""
        "},"
        "\"Values\": {"
            "\"Dpe_engineSelect\": 0,"
            "\"Dpe_is16BitMode\": 0,"
            "\"haveDVInput\": 1,"
            "\"dvme_en\": 1,"
            "\"conf_en\": 1,"
            "\"cv_en\": 1,"
            "\"occ_en\": 1,"
            "\"y_IterTimes\": 2,"
            "\"y_IterStartDirect\": 0,"
            "\"x_IterTimes_Down\": 1,"
            "\"x_IterTimes_Up\": 2,"
            "\"x_IterStartDirect_Down\": 0,"
            "\"x_IterStartDirect_Up\": 0,"
            "\"//mainEyeSel\": 0,"
            "\"//frmWidth\": 0,"
            "\"//frmHeight\": 0,"
            "\"//engWidth\": 0,"
            "\"//engHeight\": 0,"
            "\"//occWidth\": 0,"
            "\"//engStart_x\": 0,"
            "\"//engStart_y\": 0,"
            "\"//occStart_x\": 0"
        "}"
    "}, {"
        "\"Parameters\": {"
            "\"Scenario\": \"Active\""
        "},"
        "\"Values\": {"
            "\"Dpe_engineSelect\": 0,"
            "\"Dpe_is16BitMode\": 1,"
            "\"haveDVInput\": 1,"
            "\"dvme_en\": 1,"
            "\"conf_en\": 1,"
            "\"cv_en\": 1,"
            "\"occ_en\": 1,"
            "\"y_IterTimes\": 1,"
            "\"y_IterStartDirect\": 0,"
            "\"x_IterTimes_Down\": 2,"
            "\"x_IterTimes_Up\": 2,"
            "\"x_IterStartDirect_Down\": 0,"
            "\"x_IterStartDirect_Up\": 0,"
            "\"//mainEyeSel\": 0,"
            "\"//frmWidth\": 0,"
            "\"//frmHeight\": 0,"
            "\"//engWidth\": 0,"
            "\"//engHeight\": 0,"
            "\"//occWidth\": 0,"
            "\"//engStart_x\": 0,"
            "\"//engStart_y\": 0,"
            "\"//occStart_x\": 0"
        "}"
    "}],"
    "\"HW_DPE_DVS_ME\":[{"
        "\"Parameters\": {"
            "\"Scenario\": \"Preview\""
        "},"
        "\"Values\": {"
            "\"c_dv_cand_num\": 8,"
            "\"c_ord_pnlty_shift_dir\": 1,"
            "\"c_ord_pnlty_shift_num\": 1,"
            "\"c_ord_th\": 128,"
            "\"c_ord_coring\": 4,"
            "\"c_sm_dv_x_pnlty_sel\": 0,"
            "\"c_sm_dv_y_pnlty_sel\": 4,"
            "\"c_sm_dv_ada_base\": 4,"
            "\"c_sm_dv_th\": 12,"
            "\"c_sm_dv_th2\": 0,"
            "\"c_sptl_pnlty_sel\": 2,"
            "\"c_tmpr_pnlty_sel\": 2,"
            "\"c_rand_pnlty_sel\": 2,"
            "\"c_nbr_pnlty_sel\": 2,"
            "\"c_prev_pnlty_sel\": 2,"
            "\"c_gmv_pnlty_sel\": 0,"
            "\"c_refine_pnlty_sel\": 2,"
            "\"c_sptl_cost\": 1,"
            "\"c_tmpr_cost\": 3,"
            "\"c_refine_cost\": 2,"
            "\"c_nbr_cost\": 3,"
            "\"c_prev_cost\": 5,"
            "\"c_gmv_cost\": 0,"
            "\"c_rand_cost\": 16,"
            "\"c_bg_mv_th\": 160,"
            "\"c_bg_mv_pnlty_sel\": 0,"
            "\"c_bg_mv_cost\": 0,"
            "\"c_bg_mv_diff\": 32,"
            "\"c_conf_div\": 2,"
            "\"c_seed_l\": [7, 28, 32, 33, 17, 13, 11, 31],"
            "\"c_seed_r\": [7, 28, 32, 33, 17, 13, 11, 31],"
            "\"c_dv_ini_x\": 0,"
            "\"c_gmv_y1\": 0,"
            "\"c_gmv_x1\": 0,"
            "\"c_type_l\": [1, 4, 3, 3, 2, 2, 1, 6],"
            "\"c_type_r\": [1, 4, 3, 3, 2, 2, 1, 6],"
            "\"c_rand_max_mode\": 7,"
            "\"c_rand_round_offset\": 18,"
            "\"c_rand_init\": 0,"
            "\"c_rand1_vec_base_mv_shift\": 1,"
            "\"c_rand2_vec_base_mv_shift\": 1,"
            "\"c_refine_vec_base_mv_shift\": 0,"
            "\"c_rand3_vec_base_mv_shift\": 1,"
            "\"c_rand_dv\": [7, 13, 23, 29],"
            "\"c_ad_shift\": 8,"
            "\"c_lut_ad\": [0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7],"
            "\"c_seed_priority_r\": 64,"
            "\"c_seed_priority_l\": 1,"
            "\"c_sr_h\": 255,"
            "\"c_sr_v\": 8,"
            "\"c_zrv\": 0,"
            "\"c_lp_box_en\": 1,"
            "\"c_as_en\": 1,"
            "\"c_conf_mode\": 0,"
            "\"c_as_th\": 0,"
            "\"c_lut_cmlm\": [50, 40, 32, 26, 21, 16, 13, 11, 8, 7, 5, 4, 3, 3, 2, 2, 1],"
            "\"c_lut_cmlm_step\": 2,"
            "\"c_lut_conf\": [0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 6, 7, 7],"
            "\"c_bgcmmn\": 1,"
            "\"c_bgcpkrn\": 3,"
            "\"c_bgclrd\": 3,"
            "\"c_bgcmlm\": 50,"
            "\"c_wgtcmmn\": 1,"
            "\"c_wgtcpkrn\": 1,"
            "\"c_wgtclrd\": 1,"
            "\"c_wgtcmlm\": 1,"
            "\"c_divwgt\": 0,"
            "\"c_cost_validnum_th\": 7,"
            "\"//c_lp_box_l_left\": 0,"
            "\"//c_lp_box_l_right\": 0,"
            "\"//c_lp_box_l_top\": 0,"
            "\"//c_lp_box_l_bottom\": 0,"
            "\"//c_lp_box_r_left\": 0,"
            "\"//c_lp_box_r_right\": 0,"
            "\"//c_lp_box_r_top\": 0,"
            "\"//c_lp_box_r_bottom\": 0"
        "}"
    "}, {"
        "\"Parameters\": {"
            "\"Scenario\": \"Active\""
        "},"
        "\"Values\": {"
            "\"c_dv_cand_num\": 8,"
            "\"c_ord_pnlty_shift_dir\": 1,"
            "\"c_ord_pnlty_shift_num\": 1,"
            "\"c_ord_th\": 128,"
            "\"c_ord_coring\": 0,"
            "\"c_sm_dv_x_pnlty_sel\": 0,"
            "\"c_sm_dv_y_pnlty_sel\": 0,"
            "\"c_sm_dv_ada_base\": 4,"
            "\"c_sm_dv_th\": 12,"
            "\"c_sm_dv_th2\": 0,"
            "\"c_sptl_pnlty_sel\": 2,"
            "\"c_tmpr_pnlty_sel\": 2,"
            "\"c_rand_pnlty_sel\": 2,"
            "\"c_nbr_pnlty_sel\": 2,"
            "\"c_prev_pnlty_sel\": 2,"
            "\"c_gmv_pnlty_sel\": 0,"
            "\"c_refine_pnlty_sel\": 2,"
            "\"c_sptl_cost\": 1,"
            "\"c_tmpr_cost\": 3,"
            "\"c_refine_cost\": 2,"
            "\"c_nbr_cost\": 2,"
            "\"c_prev_cost\": 2,"
            "\"c_gmv_cost\": 0,"
            "\"c_rand_cost\": 8,"
            "\"c_bg_mv_th\": 160,"
            "\"c_bg_mv_pnlty_sel\": 0,"
            "\"c_bg_mv_cost\": 0,"
            "\"c_bg_mv_diff\": 32,"
            "\"c_conf_div\": 2,"
            "\"c_seed_l\": [7, 27, 32, 33, 17, 13, 11, 31],"
            "\"c_seed_r\": [7, 27, 32, 33, 17, 13, 11, 31],"
            "\"c_dv_ini_x\": 0,"
            "\"c_gmv_y1\": 0,"
            "\"c_gmv_x1\": 0,"
            "\"c_type_l\": [1, 4, 3, 3, 2, 2, 1, 6],"
            "\"c_type_r\": [1, 4, 3, 3, 2, 2, 1, 6],"
            "\"c_rand_max_mode\": 10,"
            "\"c_rand_round_offset\": 130,"
            "\"c_rand_init\": 0,"
            "\"c_rand1_vec_base_mv_shift\": 1,"
            "\"c_rand2_vec_base_mv_shift\": 1,"
            "\"c_refine_vec_base_mv_shift\": 0,"
            "\"c_rand3_vec_base_mv_shift\": 1,"
            "\"c_rand_dv\": [7, 13, 23, 29],"
            "\"c_ad_shift\": 8,"
            "\"c_lut_ad\": [0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7],"
            "\"c_seed_priority_r\": 64,"
            "\"c_seed_priority_l\": 1,"
            "\"c_sr_h\": 1023,"
            "\"c_sr_v\": 0,"
            "\"c_zrv\": 0,"
            "\"c_lp_box_en\": 1,"
            "\"c_as_en\": 1,"
            "\"c_conf_mode\": 0,"
            "\"c_as_th\": 0,"
            "\"c_lut_cmlm\": [50, 40, 32, 26, 21, 16, 13, 11, 8, 7, 5, 4, 3, 3, 2, 2, 1],"
            "\"c_lut_cmlm_step\": 2,"
            "\"c_lut_conf\": [0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 6, 7, 7],"
            "\"c_bgcmmn\": 1,"
            "\"c_bgcpkrn\": 3,"
            "\"c_bgclrd\": 3,"
            "\"c_bgcmlm\": 50,"
            "\"c_wgtcmmn\": 1,"
            "\"c_wgtcpkrn\": 1,"
            "\"c_wgtclrd\": 1,"
            "\"c_wgtcmlm\": 1,"
            "\"c_divwgt\": 0,"
            "\"c_cost_validnum_th\": 7,"
            "\"//c_lp_box_l_left\": 0,"
            "\"//c_lp_box_l_right\": 0,"
            "\"//c_lp_box_l_top\": 0,"
            "\"//c_lp_box_l_bottom\": 0,"
            "\"//c_lp_box_r_left\": 0,"
            "\"//c_lp_box_r_right\": 0,"
            "\"//c_lp_box_r_top\": 0,"
            "\"//c_lp_box_r_bottom\": 0"
        "}"
    "}],"
    "\"HW_DPE_DVS_OCC\":[{"
        "\"Parameters\": {"
            "\"Scenario\": \"Preview\""
        "},"
        "\"Values\": {"
            "\"c_lrc_sft_x\": 0,"
            "\"c_lrc_thr_h\": 3,"
            "\"c_lrc_thr_v\": 3,"
            "\"c_owc_en\": 1,"
            "\"c_owc_tlr_thr\": 3,"
            "\"c_ohf_en\": 1,"
            "\"c_ohf_tlr_thr\": 32,"
            "\"c_occ_dv_lsb_sft\": 0,"
            "\"c_occ_dv_msb_sft\": 0"
        "}"
    "}, {"
        "\"Parameters\": {"
            "\"Scenario\": \"Active\""
        "},"
        "\"Values\": {"
            "\"c_lrc_sft_x\": 0,"
            "\"c_lrc_thr_h\": 15,"
            "\"c_lrc_thr_v\": 6,"
            "\"c_owc_en\": 0,"
            "\"c_owc_tlr_thr\": 16,"
            "\"c_ohf_en\": 0,"
            "\"c_ohf_tlr_thr\": 32,"
            "\"c_occ_dv_lsb_sft\": 0,"
            "\"c_occ_dv_msb_sft\": 0"
        "}"
    "}],"
    "\"HW_DPE_DVP_CTRL\":[{"
        "\"Parameters\": {"
            "\"Scenario\": \"Preview\""
        "},"
        "\"Values\": {"
            "\"asf_en\": 1,"
            "\"Y_only\": 0,"
            "\"asf_rm_en\": 1,"
            "\"asf_rd_en\": 1,"
            "\"asf_hf_en\": 1,"
            "\"wmf_hf_en\": 1,"
            "\"wmf_filt_en\": 1,"
            "\"asf_hf_rounds\": 4,"
            "\"wmf_filt_rounds\": 1,"
            "\"asf_recursive_en\": 1,"
            "\"DV_guide_en\": 0,"
            "\"c_asf_thd_y\": 10,"
            "\"c_asf_thd_cbcr\": 6,"
            "\"c_asf_arm_ud\": 15,"
            "\"c_asf_arm_lr\": 31,"
            "\"c_rmv_mean_lut\": [4, 4, 4, 4, 4, 2, 2, 2],"
            "\"c_rmv_dsty_lut\": [10, 10, 10, 10, 10, 16, 16, 16],"
            "\"c_hf_thd\": [5, 1, 0, 0, 0, 0, 0, 0, 0, 0],"
            "\"c_hf_thin_en\": 1,"
            "\"c_hf_thd_thin\": 1,"
            "\"c_wmf_wgt_lut\": [255, 215, 182, 154, 130, 110, 93, 79, 67, 56, 48, 40, 34, 29, 24, 20, 17, 12, 9, 6, 4, 3, 2, 1, 1],"
            "\"c_hf_mode\": [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],"
            "\"//mainEyeSel\": 0,"
            "\"//frmWidth\": 0,"
            "\"//frmHeight\": 0,"
            "\"//engWidth\": 0,"
            "\"//engHeight\": 0,"
            "\"//engStart_x\": 0,"
            "\"//engStart_y\": 0"
        "}"
    "}, {"
        "\"Parameters\": {"
            "\"Scenario\": \"Active\""
        "},"
        "\"Values\": {"
            "\"asf_en\": 1,"
            "\"Y_only\": 0,"
            "\"asf_rm_en\": 0,"
            "\"asf_rd_en\": 0,"
            "\"asf_hf_en\": 1,"
            "\"wmf_hf_en\": 0,"
            "\"wmf_filt_en\": 0,"
            "\"asf_hf_rounds\": 1,"
            "\"wmf_filt_rounds\": 1,"
            "\"asf_recursive_en\": 0,"
            "\"DV_guide_en\": 1,"
            "\"c_asf_thd_y\": 56,"
            "\"c_asf_thd_cbcr\": 56,"
            "\"c_asf_arm_ud\": 5,"
            "\"c_asf_arm_lr\": 5,"
            "\"c_rmv_mean_lut\": [32, 32, 32, 32, 32, 16, 16, 16],"
            "\"c_rmv_dsty_lut\": [4, 4, 4, 4, 4, 7, 7, 7],"
            "\"c_hf_thd\": [5, 1, 0, 0, 0, 0, 0, 0, 0, 0],"
            "\"c_hf_thin_en\": 0,"
            "\"c_hf_thd_thin\": 1,"
            "\"c_wmf_wgt_lut\": [255, 215, 182, 154, 130, 110, 93, 79, 67, 56, 48, 40, 34, 29, 24, 20, 17, 12, 9, 6, 4, 3, 2, 1, 1],"
            "\"c_hf_mode\": [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],"
            "\"//mainEyeSel\": 0,"
            "\"//frmWidth\": 0,"
            "\"//frmHeight\": 0,"
            "\"//engWidth\": 0,"
            "\"//engHeight\": 0,"
            "\"//engStart_x\": 0,"
            "\"//engStart_y\": 0"
        "}"
    "}],"
    "\"HW_BOKEH\": [{"
            "\"Parameters\": {"
                "\"Strength\": \"Normal\""
            "},"
            "\"Values\": {"
                "\"CNR_BOK_BLUR_MUL\": 1,"
                "\"CNR_BOK_BLUR_SHIFT\": 0,"
                "\"CNR_BOK_BLUR_OFFSET\": 0,"
                "\"CNR_BOK_BLUR_MAX\": 14,"
                "\"CNR_BOK_BLEND_START\": 1,"
                "\"CNR_BOK_BLEND_SLOPE\": 8"
            "}"
        "}, {"
            "\"Parameters\": {"
                "\"Strength\": \"Strong\""
            "},"
            "\"Values\": {"
                "\"CNR_BOK_BLUR_MUL\": 1,"
                "\"CNR_BOK_BLUR_SHIFT\": 0,"
                "\"CNR_BOK_BLUR_OFFSET\": 0,"
                "\"CNR_BOK_BLUR_MAX\": 14,"
                "\"CNR_BOK_BLEND_START\": 1,"
                "\"CNR_BOK_BLEND_SLOPE\": 8"
            "}"
        "}],"
    "\"HW_MDP_PQ\": [{"
            "\"Parameters\": {"
                "\"MDP_PQ_Name\": \"Common\""
            "},"
            "\"Values\": {"
                "\"isRefocus\": 1,"
                "\"defaultUpTable\": 7,"
                "\"defaultDownTable\": 17,"
                "\"IBSEGain\": 0,"
                "\"switchRatio6Tap6nTap\": 1,"
                "\"switchRatio6nTapAcc\": 1"
            "}"
        "}],"
    "\"SW_ADP\": [{"
            "\"Values\": {"
                "\"adp.DvLsbShift\": 0,"
                "\"adp.DisparityShift\": 0,"
                "\"adp.DisparityShift4Color\": 0,"
                "\"adp.DebugLevel\": 0,"
                "\"adp.loglevel\": 0,"
                "\"adp.demo.dig\": 2,"
                "\"adp.demo.fill\": 0,"
                "\"adp.demo.owc\": 0,"
                "\"adp.demo.roil\": 4,"
                "\"adp.demo.roit\": 4,"
                "\"adp.demo.roir\": 267,"
                "\"adp.demo.roid\": 475,"
                "\"adp.demo.fb\": 8559,"
                "\"adp.demo.blobsize\": 40,"
                "\"adp.demo.beluma\": 40"
            "}"
        "}],"
    "\"SW_GF\": [{"
            "\"Parameters\": {"
                "\"Scenario\": \"Preview\""
            "},"
            "\"Values\": {"
                "\"GF_CoreNumber\": 1,"
                "\"ClearTable\": [1, 1, 1, 1, 1, 1, 1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 15, 20, 27, 35, 44, 54, 65, 77, 90, 94, 99, 103],"
                "\"dispCtrlPoints\": [8, 10, 12, 14, 16, 18, 20, 23, 27, 30, 33, 34, 36, 39, 41, 45, 49, 54, 60, 69, 81, 84, 87, 90, 94, 99, 103, 108],"
                "\"blurGainTable\": [55, 50, 45, 40, 35, 31, 30, 29, 28, 27, 26, 25, 24, 24, 23, 23, 23, 23, 22, 21, 18, 17, 16, 15, 13, 10, 5, 1],"
                "\"gf.logLevel\": 0,"
                "\"gf.debugLevel\": 0,"
                "\"gf.DPP_output_resize\": 1,"
                "\"gf.mode_dl\": 0,"
                "\"gf.dofptl\": 6,"
                "\"gf.dofpth\": 8,"
                "\"gf.bk_single_side\": 0,"
                "\"gf.bk_ifocus\": 10,"
                "\"gf.bk_ifocus_touch\": 5,"
                "\"gf.bk_ifocus_ratio\": 20,"
                "\"gf.be_lbound_ratio\": 0,"
                "\"gf.be_tbound_ratio\": 0,"
                "\"gf.be_rbound_ratio\": 0,"
                "\"gf.be_bbound_ratio\": 0,"
                "\"gf.be_hist_ratio\": 25,"
                "\"gf.be_depth_limit\": 128,"
                "\"gf.be_occ_dia_radius\": -1,"
                "\"gf.be_weight_spatial\": 1,"
                "\"gf.be_weight_color\": 1,"
                "\"gf.calibrate_en\": 0,"
                "\"gf.offset_en\": 0,"
                "\"gf.focus_abs_depth_max\": 128,"
                "\"gf.disp_offset\": 0,"
                "\"gf.blur_mapping_mode\": 2,"
                "\"gf.max_blur_level\": 8,"
                "\"gf.depth_domain_clr\": 180,"
                "\"gf.max_blur_gain\": 64,"
                "\"gf.min_clr\": 0,"
                "\"gf.hf\": 1,"
                "\"gf.adjust_focus\": 0,"
                "\"gf.gepf_enable\": 1,"
                "\"gf.sigma\": 2,"
                "\"gf.alpha\": 100,"
                "\"gf.wessiter\": 1,"
                "\"gf.gf_enable\": 1,"
                "\"gf.gf_w\": 1,"
                "\"gf.gf_e\": 100,"
                "\"gf.iir_enable\": 1,"
                "\"gf.sigmat\": 50,"
                "\"gf.tempbase\": 600"
            "}"
        "}],"
    "\"SW_N3D\": [{"
        "\"Parameters\": {"
            "\"Scenario\": \"Preview\""
        "},"
        "\"Values\": {"
            "\"//MaskMargin\": {"
                "\"Left\":   4,"
                "\"Right\":  4,"
                "\"Top\":    4,"
                "\"Bottom\": 4"
            "},"
            "\"//n3d.c_offset\": 0,"
            "\"//n3d.p_tune\": 0,"
            "\"//n3d.l_tune\": 0"
        "}"
    "},{"
        "\"Parameters\": {"
            "\"Scenario\": \"Capture\""
        "},"
        "\"Values\": {"
            "\"//MaskMargin\": {"
                "\"Left\":   4,"
                "\"Right\":  4,"
                "\"Top\":    4,"
                "\"Bottom\": 4"
            "},"
            "\"//n3d.c_offset\": 0,"
            "\"//n3d.p_tune\": 0,"
            "\"//n3d.l_tune\": 0"
        "}"
    "}]"
"}";
#endif
