#define IDX_DATA_YNR_LCE_LINK_DIM_NS    6
#define IDX_DATA_YNR_LCE_LINK_FACTOR_SZ    3
#define IDX_DATA_YNR_LCE_LINK_ENTRY_NS    40

static unsigned int _cam_data_entry_YNR_LCE_LINK_key0000[] = {0X000001FC, 0X80000000, 0X00016700, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0001[] = {0X00000000, 0X80300000, 0X00016700, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0002[] = {0X00000000, 0X80400000, 0X00016700, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0003[] = {0X000001FC, 0X40000000, 0X00016700, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0004[] = {0X00000000, 0X40300000, 0X00016700, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0005[] = {0X00000000, 0X40400000, 0X00016700, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0006[] = {0X000001FC, 0X80000000, 0X0001A700, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0007[] = {0X00000000, 0X80300000, 0X0001A700, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0008[] = {0X00000000, 0X80400000, 0X0001A700, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0009[] = {0X000001FC, 0X40000000, 0X0001A700, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0010[] = {0X00000000, 0X40300000, 0X0001A700, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0011[] = {0X00000000, 0X40400000, 0X0001A700, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0012[] = {0X00000001, 0X40040000, 0X000F7D02, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0013[] = {0X00000001, 0X80040000, 0X00016500, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0014[] = {0X00000001, 0X00040000, 0X000F7D01, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0015[] = {0X00000001, 0X40040000, 0X000FBD02, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0016[] = {0X00000001, 0X80040000, 0X0001A500, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0017[] = {0X00000001, 0X00040000, 0X000FBD01, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0018[] = {0X00000002, 0X40080000, 0X000FFD02, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0019[] = {0X00000002, 0X00080000, 0X000FFD01, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0020[] = {0X00CC0000, 0XC0000000, 0X000FFFFF, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0021[] = {0X03300000, 0XC0000000, 0X000FFFFF, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0022[] = {0XFC000000, 0XC000000F, 0X000FC7FF, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0023[] = {0X00000600, 0XC0000000, 0X000FFFFF, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0024[] = {0X00001800, 0XC0000000, 0X000FFFFF, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0025[] = {0X0001E000, 0XC0000000, 0X000FC7FF, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0026[] = {0X0001E1FC, 0XC0000000, 0X000FDBFF, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0027[] = {0X00000000, 0XC0300000, 0X000FDBFF, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0028[] = {0X00000000, 0XC0400000, 0X000FDBFF, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0029[] = {0X00000001, 0X80040000, 0X00015900, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0030[] = {0X00000001, 0X80040000, 0X00019900, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0031[] = {0X000001FC, 0X80000000, 0X0006FF00, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0032[] = {0X00000000, 0X80300000, 0X0006FF00, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0033[] = {0X00000000, 0X80400000, 0X0006FF00, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0034[] = {0X00000001, 0X80040000, 0X0006FF00, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0035[] = {0XFFFFFFFF, 0XBFFFFFFF, 0X000FFF00, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0036[] = {0X00000000, 0X80300000, 0X000FFF00, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0037[] = {0X00000000, 0X80400000, 0X000FFF00, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0038[] = {0XFFFFFFFF, 0X7FFFFFFF, 0X000FFFF8, };
static unsigned int _cam_data_entry_YNR_LCE_LINK_key0039[] = {0XFFFFFFFF, 0X3FFFFFFF, 0X000FFF07, };

static IDX_MASK_ENTRY _cam_data_entry_YNR_LCE_LINK[IDX_DATA_YNR_LCE_LINK_ENTRY_NS] =
{
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0000, 0, 0, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0001, 8, 0, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0002, 16, 0, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0003, 0, 1, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0004, 8, 1, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0005, 16, 1, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0006, 24, 2, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0007, 8, 2, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0008, 16, 2, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0009, 24, 3, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0010, 8, 3, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0011, 16, 3, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0012, 32, 4, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0013, 32, 5, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0014, 40, 6, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0015, 32, 7, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0016, 32, 8, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0017, 40, 9, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0018, 48, 10, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0019, 48, 11, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0020, 32, 12, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0021, 48, 13, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0022, 0, 14, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0023, 32, 15, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0024, 48, 16, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0025, 0, 17, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0026, 0, 18, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0027, 8, 18, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0028, 16, 18, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0029, 32, 19, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0030, 32, 20, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0031, 0, 22, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0032, 8, 22, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0033, 16, 22, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0034, 32, 23, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0035, 0, 24, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0036, 8, 24, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0037, 16, 24, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0038, 32, 25, 0, 0},
    {(unsigned int*)&_cam_data_entry_YNR_LCE_LINK_key0039, 48, 26, 0, 0},
};

static unsigned short _cam_data_dims_YNR_LCE_LINK[] = 
{
    EDim_IspProfile,
    EDim_SensorMode,
    EDim_FrontBin,
    EDim_Flash,
    EDim_FaceDetection,
    EDim_Zoom,
};

static unsigned short _cam_data_expand_YNR_LCE_LINK[] = 
{0, 0, 1};

const IDX_MASK_T cam_data_YNR_LCE_LINK =
{
    {IDX_ALGO_MASK, IDX_DATA_YNR_LCE_LINK_DIM_NS, (unsigned short*)&_cam_data_dims_YNR_LCE_LINK, (unsigned short*)&_cam_data_expand_YNR_LCE_LINK},
    {IDX_DATA_YNR_LCE_LINK_ENTRY_NS, IDX_DATA_YNR_LCE_LINK_FACTOR_SZ, (IDX_MASK_ENTRY*)&_cam_data_entry_YNR_LCE_LINK}
};