#define IDX_DATA_CNR_CNR_DIM_NS    4
#define IDX_DATA_CNR_CNR_FACTOR_SZ    3
#define IDX_DATA_CNR_CNR_ENTRY_NS    56

static unsigned int _cam_data_entry_CNR_CNR_key0000[] = {0X0000000C, 0X80000000, 0X00001100, };
static unsigned int _cam_data_entry_CNR_CNR_key0001[] = {0X00000020, 0X80000000, 0X00001100, };
static unsigned int _cam_data_entry_CNR_CNR_key0002[] = {0X00000040, 0X80000000, 0X00001100, };
static unsigned int _cam_data_entry_CNR_CNR_key0003[] = {0X00000100, 0X80000000, 0X00001100, };
static unsigned int _cam_data_entry_CNR_CNR_key0004[] = {0X00000000, 0X80300000, 0X00001100, };
static unsigned int _cam_data_entry_CNR_CNR_key0005[] = {0X00000000, 0X80400000, 0X00001100, };
static unsigned int _cam_data_entry_CNR_CNR_key0006[] = {0X0000000C, 0X40000000, 0X00001100, };
static unsigned int _cam_data_entry_CNR_CNR_key0007[] = {0X00000020, 0X40000000, 0X00001100, };
static unsigned int _cam_data_entry_CNR_CNR_key0008[] = {0X00000040, 0X40000000, 0X00001100, };
static unsigned int _cam_data_entry_CNR_CNR_key0009[] = {0X00000100, 0X40000000, 0X00001100, };
static unsigned int _cam_data_entry_CNR_CNR_key0010[] = {0X00000000, 0X40300000, 0X00001100, };
static unsigned int _cam_data_entry_CNR_CNR_key0011[] = {0X00000000, 0X40400000, 0X00001100, };
static unsigned int _cam_data_entry_CNR_CNR_key0012[] = {0X0000000C, 0X80000000, 0X00002100, };
static unsigned int _cam_data_entry_CNR_CNR_key0013[] = {0X00000020, 0X80000000, 0X00002100, };
static unsigned int _cam_data_entry_CNR_CNR_key0014[] = {0X00000040, 0X80000000, 0X00002100, };
static unsigned int _cam_data_entry_CNR_CNR_key0015[] = {0X00000100, 0X80000000, 0X00002100, };
static unsigned int _cam_data_entry_CNR_CNR_key0016[] = {0X00000000, 0X80300000, 0X00002100, };
static unsigned int _cam_data_entry_CNR_CNR_key0017[] = {0X00000000, 0X80400000, 0X00002100, };
static unsigned int _cam_data_entry_CNR_CNR_key0018[] = {0X0000000C, 0X40000000, 0X00002100, };
static unsigned int _cam_data_entry_CNR_CNR_key0019[] = {0X00000020, 0X40000000, 0X00002100, };
static unsigned int _cam_data_entry_CNR_CNR_key0020[] = {0X00000040, 0X40000000, 0X00002100, };
static unsigned int _cam_data_entry_CNR_CNR_key0021[] = {0X00000100, 0X40000000, 0X00002100, };
static unsigned int _cam_data_entry_CNR_CNR_key0022[] = {0X00000000, 0X40300000, 0X00002100, };
static unsigned int _cam_data_entry_CNR_CNR_key0023[] = {0X00000000, 0X40400000, 0X00002100, };
static unsigned int _cam_data_entry_CNR_CNR_key0024[] = {0X00000001, 0X40040000, 0X00001F02, };
static unsigned int _cam_data_entry_CNR_CNR_key0025[] = {0X00000001, 0X80040000, 0X00001100, };
static unsigned int _cam_data_entry_CNR_CNR_key0026[] = {0X00000001, 0X00040000, 0X00001F01, };
static unsigned int _cam_data_entry_CNR_CNR_key0027[] = {0X00000001, 0X40040000, 0X00002F00, };
static unsigned int _cam_data_entry_CNR_CNR_key0028[] = {0X00000001, 0X80040000, 0X00002100, };
static unsigned int _cam_data_entry_CNR_CNR_key0029[] = {0X00000001, 0X00040000, 0X00002F01, };
static unsigned int _cam_data_entry_CNR_CNR_key0030[] = {0X00000002, 0X40080000, 0X00003F02, };
static unsigned int _cam_data_entry_CNR_CNR_key0031[] = {0X00000002, 0X00080000, 0X00003F01, };
static unsigned int _cam_data_entry_CNR_CNR_key0032[] = {0X00000000, 0XC0000330, 0X00003FFF, };
static unsigned int _cam_data_entry_CNR_CNR_key0033[] = {0X00000000, 0XC0000CC0, 0X00003FFF, };
static unsigned int _cam_data_entry_CNR_CNR_key0034[] = {0X00000000, 0XC001B000, 0X000031FF, };
static unsigned int _cam_data_entry_CNR_CNR_key0035[] = {0X00CC0000, 0XC0000000, 0X00003FFF, };
static unsigned int _cam_data_entry_CNR_CNR_key0036[] = {0X03300000, 0XC0000000, 0X00003FFF, };
static unsigned int _cam_data_entry_CNR_CNR_key0037[] = {0X6C000000, 0XC0000000, 0X000031FF, };
static unsigned int _cam_data_entry_CNR_CNR_key0038[] = {0X00000000, 0XC0000001, 0X000031FF, };
static unsigned int _cam_data_entry_CNR_CNR_key0039[] = {0X00000000, 0XC0000002, 0X000031FF, };
static unsigned int _cam_data_entry_CNR_CNR_key0040[] = {0X00000000, 0XC0000008, 0X000031FF, };
static unsigned int _cam_data_entry_CNR_CNR_key0041[] = {0X00000600, 0XC0000000, 0X00003FFF, };
static unsigned int _cam_data_entry_CNR_CNR_key0042[] = {0X00001800, 0XC0000000, 0X00003FFF, };
static unsigned int _cam_data_entry_CNR_CNR_key0043[] = {0X0001E000, 0XC0000000, 0X000031FF, };
static unsigned int _cam_data_entry_CNR_CNR_key0044[] = {0X0001E00C, 0XC0000000, 0X000036FF, };
static unsigned int _cam_data_entry_CNR_CNR_key0045[] = {0X00000020, 0XC0000000, 0X000036FF, };
static unsigned int _cam_data_entry_CNR_CNR_key0046[] = {0X00000040, 0XC0000000, 0X000036FF, };
static unsigned int _cam_data_entry_CNR_CNR_key0047[] = {0X00000100, 0XC0000000, 0X000036FF, };
static unsigned int _cam_data_entry_CNR_CNR_key0048[] = {0X00000000, 0XC0300000, 0X000036FF, };
static unsigned int _cam_data_entry_CNR_CNR_key0049[] = {0X00000000, 0XC0400000, 0X000036FF, };
static unsigned int _cam_data_entry_CNR_CNR_key0050[] = {0X6C000000, 0XC001B000, 0X000036FF, };
static unsigned int _cam_data_entry_CNR_CNR_key0051[] = {0X00000000, 0XC0000001, 0X000036FF, };
static unsigned int _cam_data_entry_CNR_CNR_key0052[] = {0X00000000, 0XC0000002, 0X000036FF, };
static unsigned int _cam_data_entry_CNR_CNR_key0053[] = {0X00000000, 0XC0000008, 0X000036FF, };
static unsigned int _cam_data_entry_CNR_CNR_key0054[] = {0X00000001, 0X80040000, 0X00001600, };
static unsigned int _cam_data_entry_CNR_CNR_key0055[] = {0X00000001, 0X80040000, 0X00002600, };

static IDX_MASK_ENTRY _cam_data_entry_CNR_CNR[IDX_DATA_CNR_CNR_ENTRY_NS] =
{
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0000, 0, 0, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0001, 8, 0, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0002, 16, 0, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0003, 24, 0, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0004, 32, 0, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0005, 40, 0, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0006, 0, 1, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0007, 8, 1, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0008, 16, 1, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0009, 24, 1, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0010, 32, 1, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0011, 40, 1, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0012, 48, 2, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0013, 56, 2, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0014, 64, 2, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0015, 72, 2, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0016, 32, 2, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0017, 40, 2, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0018, 48, 3, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0019, 56, 3, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0020, 64, 3, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0021, 72, 3, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0022, 32, 3, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0023, 40, 3, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0024, 80, 4, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0025, 80, 5, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0026, 80, 6, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0027, 80, 7, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0028, 80, 8, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0029, 80, 9, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0030, 88, 10, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0031, 88, 11, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0032, 80, 12, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0033, 88, 13, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0034, 0, 14, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0035, 80, 15, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0036, 88, 16, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0037, 0, 17, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0038, 8, 17, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0039, 16, 17, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0040, 24, 17, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0041, 80, 18, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0042, 88, 19, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0043, 0, 20, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0044, 0, 21, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0045, 8, 21, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0046, 16, 21, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0047, 24, 21, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0048, 32, 21, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0049, 40, 21, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0050, 0, 22, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0051, 8, 22, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0052, 16, 22, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0053, 24, 22, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0054, 80, 23, 0, 0},
    {(unsigned int*)&_cam_data_entry_CNR_CNR_key0055, 80, 24, 0, 0},
};

static unsigned short _cam_data_dims_CNR_CNR[] = 
{
    EDim_IspProfile,
    EDim_SensorMode,
    EDim_Flash,
    EDim_FaceDetection,
};

static unsigned short _cam_data_expand_CNR_CNR[] = 
{0, 0, 1};

const IDX_MASK_T cam_data_CNR_CNR =
{
    {IDX_ALGO_MASK, IDX_DATA_CNR_CNR_DIM_NS, (unsigned short*)&_cam_data_dims_CNR_CNR, (unsigned short*)&_cam_data_expand_CNR_CNR},
    {IDX_DATA_CNR_CNR_ENTRY_NS, IDX_DATA_CNR_CNR_FACTOR_SZ, (IDX_MASK_ENTRY*)&_cam_data_entry_CNR_CNR}
};