/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 */
/* MediaTek Inc. (C) 2017. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

/********************************************************************************************
 *     LEGAL DISCLAIMER
 *
 *     (Header of MediaTek Software/Firmware Release or Documentation)
 *
 *     BY OPENING OR USING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 *     THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE") RECEIVED
 *     FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON AN "AS-IS" BASIS
 *     ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED,
 *     INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR
 *     A PARTICULAR PURPOSE OR NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY
 *     WHATSOEVER WITH RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 *     INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK
 *     ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
 *     NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S SPECIFICATION
 *     OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
 *
 *     BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE LIABILITY WITH
 *     RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION,
 *      *     TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE
 *     FEES OR SERVICE CHARGE PAID BY BUYER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 *     THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE WITH THE LAWS
 *     OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF LAWS PRINCIPLES.
 ************************************************************************************************/
#ifndef _CFG_ISP_TUNING_IDX_PREVIEW_H_
#define _CFG_ISP_TUNING_IDX_PREVIEW_H_

#include <mtkcam/utils/metadata/client/mtk_metadata_tag.h>

#define PREVIEW_SCENE_MODE_CONFIG(sensor, scene)\
    IDX_MODE_Preview(sensor, scene, eIDX_ISO_100)\
    IdxSet<EIspProfile_Preview, sensor, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_100>::idx;\
    IDX_MODE_Preview(sensor, scene, eIDX_ISO_200)\
    IdxSet<EIspProfile_Preview, sensor, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_200>::idx;\
    IDX_MODE_Preview(sensor, scene, eIDX_ISO_400)\
    IdxSet<EIspProfile_Preview, sensor, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_400>::idx;\
    IDX_MODE_Preview(sensor, scene, eIDX_ISO_800)\
    IdxSet<EIspProfile_Preview, sensor, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_800>::idx;\
    IDX_MODE_Preview(sensor, scene, eIDX_ISO_1200)\
    IdxSet<EIspProfile_Preview, sensor, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1200>::idx;\
    IDX_MODE_Preview(sensor, scene, eIDX_ISO_1600)\
    IdxSet<EIspProfile_Preview, sensor, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1600>::idx;\
    IDX_MODE_Preview(sensor, scene, eIDX_ISO_2000)\
    IdxSet<EIspProfile_Preview, sensor, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2000>::idx;\
    IDX_MODE_Preview(sensor, scene, eIDX_ISO_2400)\
    IdxSet<EIspProfile_Preview, sensor, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2400>::idx;\
    IDX_MODE_Preview(sensor, scene, eIDX_ISO_2800)\
    IdxSet<EIspProfile_Preview, sensor, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2800>::idx;\
    IDX_MODE_Preview(sensor, scene, eIDX_ISO_3200)\
    IdxSet<EIspProfile_Preview, sensor, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_3200>::idx;\

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Preview> <Sensor Mode: Preview>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_UNSUPPORTED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Preview( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_100 )
IDX_SET( DBS:0, OBC:0, BPC:0, NR1:0, PDC:0,  UDM:0, GGM:0, ANR:0, ANR2:0, CCR:0, BOK:0, EE:0, NR3D:0, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Preview( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_200 )
IDX_SET( DBS:1, OBC:0, BPC:1, NR1:1, PDC:1,  UDM:1, GGM:0, ANR:1, ANR2:1, CCR:1, BOK:0, EE:1, NR3D:1, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Preview( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_400 )
IDX_SET( DBS:2, OBC:0, BPC:2, NR1:2, PDC:2,  UDM:2, GGM:0, ANR:2, ANR2:2, CCR:2, BOK:1, EE:2, NR3D:2, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Preview( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_800 )
IDX_SET( DBS:3, OBC:1, BPC:3, NR1:3, PDC:3,  UDM:3, GGM:0, ANR:3, ANR2:3, CCR:3, BOK:1, EE:3, NR3D:3, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Preview( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1200 )
IDX_SET( DBS:4, OBC:1, BPC:4, NR1:4, PDC:4,  UDM:4, GGM:0, ANR:4, ANR2:4, CCR:4, BOK:2, EE:4, NR3D:4, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Preview( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1600 )
IDX_SET( DBS:5, OBC:1, BPC:5, NR1:5, PDC:5,  UDM:5, GGM:0, ANR:5, ANR2:5, CCR:5, BOK:2, EE:5, NR3D:5, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Preview( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2000 )
IDX_SET( DBS:6, OBC:1, BPC:6, NR1:6, PDC:6,  UDM:6, GGM:0, ANR:6, ANR2:6, CCR:6, BOK:3, EE:6, NR3D:6, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Preview( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2400 )
IDX_SET( DBS:7, OBC:1, BPC:7, NR1:7, PDC:7,  UDM:7, GGM:0, ANR:7, ANR2:7, CCR:7, BOK:3, EE:7, NR3D:7, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Preview( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2800 )
IDX_SET( DBS:8, OBC:1, BPC:8, NR1:8, PDC:8,  UDM:8, GGM:0, ANR:8, ANR2:8, CCR:8, BOK:4, EE:8, NR3D:8, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Preview( ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_3200 )
IDX_SET( DBS:9, OBC:1, BPC:9, NR1:9, PDC:9,  UDM:9, GGM:0, ANR:9, ANR2:9, CCR:9, BOK:4, EE:9, NR3D:9, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_NORMAL)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_ACTION)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_NIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_THEATRE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_BEACH)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_SNOW)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_SUNSET)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_FIREWORKS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_SPORTS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_PARTY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_HDR)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Preview, MTK_CONTROL_SCENE_MODE_BARCODE)


//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Preview> <Sensor Mode: Capture>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_UNSUPPORTED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Preview( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_100 )
IDX_SET( DBS:10, OBC:2, BPC:10, NR1:10, PDC:10,  UDM:10, GGM:0, ANR:10, ANR2:10, CCR:0, BOK:5, EE:10, NR3D:10, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Preview( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_200 )
IDX_SET( DBS:11, OBC:2, BPC:11, NR1:11, PDC:11,  UDM:11, GGM:0, ANR:11, ANR2:11, CCR:1, BOK:5, EE:11, NR3D:11, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Preview( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_400 )
IDX_SET( DBS:12, OBC:2, BPC:12, NR1:12, PDC:12,  UDM:12, GGM:0, ANR:12, ANR2:12, CCR:2, BOK:6, EE:12, NR3D:12, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Preview( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_800 )
IDX_SET( DBS:13, OBC:3, BPC:13, NR1:13, PDC:13,  UDM:13, GGM:0, ANR:13, ANR2:13, CCR:3, BOK:6, EE:13, NR3D:13, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Preview( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1200 )
IDX_SET( DBS:14, OBC:3, BPC:14, NR1:14, PDC:14,  UDM:14, GGM:0, ANR:14, ANR2:14, CCR:4, BOK:7, EE:14, NR3D:14, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Preview( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1600 )
IDX_SET( DBS:15, OBC:3, BPC:15, NR1:15, PDC:15,  UDM:15, GGM:0, ANR:15, ANR2:15, CCR:5, BOK:7, EE:15, NR3D:15, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Preview( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2000 )
IDX_SET( DBS:16, OBC:3, BPC:16, NR1:16, PDC:16,  UDM:16, GGM:0, ANR:16, ANR2:16, CCR:6, BOK:8, EE:16, NR3D:16, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Preview( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2400 )
IDX_SET( DBS:17, OBC:3, BPC:17, NR1:17, PDC:17,  UDM:17, GGM:0, ANR:17, ANR2:17, CCR:7, BOK:8, EE:17, NR3D:17, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Preview( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2800 )
IDX_SET( DBS:18, OBC:3, BPC:18, NR1:18, PDC:18,  UDM:18, GGM:0, ANR:18, ANR2:18, CCR:8, BOK:9, EE:18, NR3D:18, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Preview( ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_3200 )
IDX_SET( DBS:19, OBC:3, BPC:19, NR1:19, PDC:19,  UDM:19, GGM:0, ANR:19, ANR2:19, CCR:9, BOK:9, EE:19, NR3D:19, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_NORMAL)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_ACTION)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_NIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_THEATRE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_BEACH)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_SNOW)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_SUNSET)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_FIREWORKS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_SPORTS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_PARTY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_HDR)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Capture, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Preview> <Sensor Mode: Video>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_UNSUPPORTED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Preview( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_100 )
IDX_SET( DBS:20, OBC:4, BPC:20, NR1:20, PDC:20,  UDM:20, GGM:0, ANR:20, ANR2:20, CCR:0, BOK:10, EE:20, NR3D:20, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Preview( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_200 )
IDX_SET( DBS:21, OBC:4, BPC:21, NR1:21, PDC:21,  UDM:21, GGM:0, ANR:21, ANR2:21, CCR:1, BOK:10, EE:21, NR3D:21, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Preview( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_400 )
IDX_SET( DBS:22, OBC:4, BPC:22, NR1:22, PDC:22,  UDM:22, GGM:0, ANR:22, ANR2:22, CCR:2, BOK:11, EE:22, NR3D:22, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Preview( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_800 )
IDX_SET( DBS:23, OBC:5, BPC:23, NR1:23, PDC:23,  UDM:23, GGM:0, ANR:23, ANR2:23, CCR:3, BOK:11, EE:23, NR3D:23, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Preview( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1200 )
IDX_SET( DBS:24, OBC:5, BPC:24, NR1:24, PDC:24,  UDM:24, GGM:0, ANR:24, ANR2:24, CCR:4, BOK:12, EE:24, NR3D:24, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Preview( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1600 )
IDX_SET( DBS:25, OBC:5, BPC:25, NR1:25, PDC:25,  UDM:25, GGM:0, ANR:25, ANR2:25, CCR:5, BOK:12, EE:25, NR3D:25, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Preview( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2000 )
IDX_SET( DBS:26, OBC:5, BPC:26, NR1:26, PDC:26,  UDM:26, GGM:0, ANR:26, ANR2:26, CCR:6, BOK:13, EE:26, NR3D:26, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Preview( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2400 )
IDX_SET( DBS:27, OBC:5, BPC:27, NR1:27, PDC:27,  UDM:27, GGM:0, ANR:27, ANR2:27, CCR:7, BOK:13, EE:27, NR3D:27, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Preview( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2800 )
IDX_SET( DBS:28, OBC:5, BPC:28, NR1:28, PDC:28,  UDM:28, GGM:0, ANR:28, ANR2:28, CCR:8, BOK:14, EE:28, NR3D:28, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Preview( ESensorMode_Video, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_3200 )
IDX_SET( DBS:29, OBC:5, BPC:29, NR1:29, PDC:29,  UDM:29, GGM:0, ANR:29, ANR2:29, CCR:9, BOK:14, EE:29, NR3D:29, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_NORMAL)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_ACTION)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_NIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_THEATRE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_BEACH)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_SNOW)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_SUNSET)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_FIREWORKS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_SPORTS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_PARTY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_HDR)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Video, MTK_CONTROL_SCENE_MODE_BARCODE)


//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Preview> <Sensor Mode: SlimVideo1>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_UNSUPPORTED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Preview( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_100 )
IDX_SET( DBS:30 ,OBC:6, BPC:30, NR1:30, PDC:30,  UDM:30, GGM:0, ANR:30, ANR2:30, CCR:0, BOK:15, EE:30, NR3D:30, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Preview( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_200 )
IDX_SET( DBS:31, OBC:6, BPC:31, NR1:31, PDC:31,  UDM:31, GGM:0, ANR:31, ANR2:31, CCR:1, BOK:15, EE:31, NR3D:31, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Preview( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_400 )
IDX_SET( DBS:32, OBC:6, BPC:32, NR1:32, PDC:32,  UDM:32, GGM:0, ANR:32, ANR2:32, CCR:2, BOK:16, EE:32, NR3D:32, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Preview( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_800 )
IDX_SET( DBS:33, OBC:7, BPC:33, NR1:33, PDC:33,  UDM:33, GGM:0, ANR:33, ANR2:33, CCR:3, BOK:16, EE:33, NR3D:33, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Preview( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1200 )
IDX_SET( DBS:34, OBC:7, BPC:34, NR1:34, PDC:34,  UDM:34, GGM:0, ANR:34, ANR2:34, CCR:4, BOK:17, EE:34, NR3D:34, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Preview( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1600 )
IDX_SET( DBS:35, OBC:7, BPC:35, NR1:35, PDC:35,  UDM:35, GGM:0, ANR:35, ANR2:35, CCR:5, BOK:17, EE:35, NR3D:35, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Preview( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2000 )
IDX_SET( DBS:36, OBC:7, BPC:36, NR1:36, PDC:36,  UDM:36, GGM:0, ANR:36, ANR2:36, CCR:6, BOK:18, EE:36, NR3D:36, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Preview( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2400 )
IDX_SET( DBS:37, OBC:7, BPC:37, NR1:37, PDC:37,  UDM:37, GGM:0, ANR:37, ANR2:37, CCR:7, BOK:18, EE:37, NR3D:37, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Preview( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2800 )
IDX_SET( DBS:38, OBC:7, BPC:38, NR1:38, PDC:38,  UDM:38, GGM:0, ANR:38, ANR2:38, CCR:8, BOK:19, EE:38, NR3D:38, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Preview( ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_3200 )
IDX_SET( DBS:39, OBC:7, BPC:39, NR1:39, PDC:39,  UDM:39, GGM:0, ANR:39, ANR2:39, CCR:9, BOK:19, EE:39, NR3D:39, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_NORMAL)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_ACTION)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_NIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_THEATRE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_BEACH)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_SNOW)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_SUNSET)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_FIREWORKS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_SPORTS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_PARTY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_HDR)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo1, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Preview> <Sensor Mode: SlimVideo2>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_UNSUPPORTED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Preview( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_100 )
IDX_SET( DBS:40, OBC:8, BPC:40, NR1:40, PDC:40,  UDM:40, GGM:0, ANR:40, ANR2:40, CCR:0, BOK:20, EE:40, NR3D:40, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Preview( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_200 )
IDX_SET( DBS:41, OBC:8, BPC:41, NR1:41, PDC:41,  UDM:41, GGM:0, ANR:41, ANR2:41, CCR:1, BOK:20, EE:41, NR3D:41, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Preview( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_400 )
IDX_SET( DBS:42, OBC:8, BPC:42, NR1:42, PDC:42,  UDM:42, GGM:0, ANR:42, ANR2:42, CCR:2, BOK:21, EE:42, NR3D:42, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Preview( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_800 )
IDX_SET( DBS:43, OBC:9, BPC:43, NR1:43, PDC:43,  UDM:43, GGM:0, ANR:43, ANR2:43, CCR:3, BOK:21, EE:43, NR3D:43, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Preview( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1200 )
IDX_SET( DBS:44, OBC:9, BPC:44, NR1:44, PDC:44,  UDM:44, GGM:0, ANR:44, ANR2:44, CCR:4, BOK:22, EE:44, NR3D:44, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Preview( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1600 )
IDX_SET( DBS:45, OBC:9, BPC:45, NR1:45, PDC:45,  UDM:45, GGM:0, ANR:45, ANR2:45, CCR:5, BOK:22, EE:45, NR3D:45, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Preview( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2000 )
IDX_SET( DBS:46, OBC:9, BPC:46, NR1:46, PDC:46,  UDM:46, GGM:0, ANR:46, ANR2:46, CCR:6, BOK:23, EE:46, NR3D:46, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Preview( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2400 )
IDX_SET( DBS:47, OBC:9, BPC:47, NR1:47, PDC:47,  UDM:47, GGM:0, ANR:47, ANR2:47, CCR:7, BOK:23, EE:47, NR3D:47, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Preview( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2800 )
IDX_SET( DBS:48, OBC:9, BPC:48, NR1:48, PDC:48,  UDM:48, GGM:0, ANR:48, ANR2:48, CCR:8, BOK:24, EE:48, NR3D:48, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Preview( ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_3200 )
IDX_SET( DBS:49, OBC:9, BPC:49, NR1:49, PDC:49,  UDM:49, GGM:0, ANR:49, ANR2:49, CCR:9, BOK:24, EE:49, NR3D:49, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_NORMAL)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_ACTION)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_NIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_THEATRE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_BEACH)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_SNOW)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_SUNSET)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_FIREWORKS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_SPORTS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_PARTY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_HDR)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_SlimVideo2, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Preview> <Sensor Mode: Custom1>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_UNSUPPORTED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Preview( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_100 )
IDX_SET( DBS:200, OBC:40, BPC:200, NR1:180, PDC:180,  UDM:200, GGM:0, ANR:260, ANR2:260, CCR:0, BOK:25, EE:220, NR3D:140, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Preview( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_200 )
IDX_SET( DBS:201, OBC:40, BPC:201, NR1:181, PDC:181,  UDM:201, GGM:0, ANR:261, ANR2:261, CCR:1, BOK:25, EE:221, NR3D:141, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Preview( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_400 )
IDX_SET( DBS:202, OBC:40, BPC:202, NR1:182, PDC:182,  UDM:202, GGM:0, ANR:262, ANR2:262, CCR:2, BOK:26, EE:222, NR3D:142, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Preview( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_800 )
IDX_SET( DBS:203, OBC:41, BPC:203, NR1:183, PDC:183,  UDM:203, GGM:0, ANR:263, ANR2:263, CCR:3, BOK:26, EE:223, NR3D:143, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Preview( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1200 )
IDX_SET( DBS:204, OBC:41, BPC:204, NR1:184, PDC:184,  UDM:204, GGM:0, ANR:264, ANR2:264, CCR:4, BOK:27, EE:224, NR3D:144, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Preview( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1600 )
IDX_SET( DBS:205, OBC:41, BPC:205, NR1:185, PDC:185,  UDM:205, GGM:0, ANR:265, ANR2:265, CCR:5, BOK:27, EE:225, NR3D:145, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Preview( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2000 )
IDX_SET( DBS:206, OBC:41, BPC:206, NR1:186, PDC:186,  UDM:206, GGM:0, ANR:266, ANR2:266, CCR:6, BOK:28, EE:226, NR3D:146, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Preview( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2400 )
IDX_SET( DBS:207, OBC:41, BPC:207, NR1:187, PDC:187,  UDM:207, GGM:0, ANR:267, ANR2:267, CCR:7, BOK:28, EE:227, NR3D:147, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Preview( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2800 )
IDX_SET( DBS:208, OBC:41, BPC:208, NR1:188, PDC:188,  UDM:208, GGM:0, ANR:268, ANR2:268, CCR:8, BOK:29, EE:228, NR3D:148, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Preview( ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_3200 )
IDX_SET( DBS:209, OBC:41, BPC:209, NR1:189, PDC:189,  UDM:209, GGM:0, ANR:269, ANR2:269, CCR:9, BOK:29, EE:229, NR3D:149, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_NORMAL)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_ACTION)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_NIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_THEATRE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_BEACH)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_SNOW)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_SUNSET)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_FIREWORKS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_SPORTS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_PARTY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_HDR)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom1, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Preview> <Sensor Mode: Custom2>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_UNSUPPORTED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Preview( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_100 )
IDX_SET( DBS:210, OBC:42, BPC:210, NR1:190, PDC:190,  UDM:210, GGM:0, ANR:270, ANR2:270, CCR:0, BOK:30, EE:230, NR3D:150, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Preview( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_200 )
IDX_SET( DBS:211, OBC:42, BPC:211, NR1:191, PDC:191,  UDM:211, GGM:0, ANR:271, ANR2:271, CCR:1, BOK:30, EE:231, NR3D:151, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Preview( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_400 )
IDX_SET( DBS:212, OBC:42, BPC:212, NR1:192, PDC:192,  UDM:212, GGM:0, ANR:272, ANR2:272, CCR:2, BOK:31, EE:232, NR3D:152, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Preview( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_800 )
IDX_SET( DBS:213, OBC:43, BPC:213, NR1:193, PDC:193,  UDM:213, GGM:0, ANR:273, ANR2:273, CCR:3, BOK:31, EE:233, NR3D:153, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Preview( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1200 )
IDX_SET( DBS:214, OBC:43, BPC:214, NR1:194, PDC:194,  UDM:214, GGM:0, ANR:274, ANR2:274, CCR:4, BOK:32, EE:234, NR3D:154, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Preview( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1600 )
IDX_SET( DBS:215, OBC:43, BPC:215, NR1:195, PDC:195,  UDM:215, GGM:0, ANR:275, ANR2:275, CCR:5, BOK:32, EE:235, NR3D:155, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Preview( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2000 )
IDX_SET( DBS:216, OBC:43, BPC:216, NR1:196, PDC:196,  UDM:216, GGM:0, ANR:276, ANR2:276, CCR:6, BOK:33, EE:236, NR3D:156, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Preview( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2400 )
IDX_SET( DBS:217, OBC:43, BPC:217, NR1:197, PDC:197,  UDM:217, GGM:0, ANR:277, ANR2:277, CCR:7, BOK:33, EE:237, NR3D:157, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Preview( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2800 )
IDX_SET( DBS:218, OBC:43, BPC:218, NR1:198, PDC:198,  UDM:218, GGM:0, ANR:278, ANR2:278, CCR:8, BOK:34, EE:238, NR3D:158, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Preview( ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_3200 )
IDX_SET( DBS:219, OBC:43, BPC:219, NR1:199, PDC:199,  UDM:219, GGM:0, ANR:279, ANR2:279, CCR:9, BOK:34, EE:239, NR3D:159, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_NORMAL)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_ACTION)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_NIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_THEATRE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_BEACH)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_SNOW)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_SUNSET)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_FIREWORKS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_SPORTS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_PARTY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_HDR)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom2, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Preview> <Sensor Mode: Custom3>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_UNSUPPORTED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Preview( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_100 )
IDX_SET( DBS:220, OBC:44, BPC:220, NR1:200, PDC:200,  UDM:220, GGM:0, ANR:280, ANR2:280, CCR:0, BOK:35, EE:240, NR3D:160, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Preview( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_200 )
IDX_SET( DBS:221, OBC:44, BPC:221, NR1:201, PDC:201,  UDM:221, GGM:0, ANR:281, ANR2:281, CCR:1, BOK:35, EE:241, NR3D:161, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Preview( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_400 )
IDX_SET( DBS:222, OBC:44, BPC:222, NR1:202, PDC:202,  UDM:222, GGM:0, ANR:282, ANR2:282, CCR:2, BOK:36, EE:242, NR3D:162, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Preview( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_800 )
IDX_SET( DBS:223, OBC:45, BPC:223, NR1:203, PDC:203,  UDM:223, GGM:0, ANR:283, ANR2:283, CCR:3, BOK:36, EE:243, NR3D:163, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Preview( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1200 )
IDX_SET( DBS:224, OBC:45, BPC:224, NR1:204, PDC:204,  UDM:224, GGM:0, ANR:284, ANR2:284, CCR:4, BOK:37, EE:244, NR3D:164, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Preview( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1600 )
IDX_SET( DBS:225, OBC:45, BPC:225, NR1:205, PDC:205,  UDM:225, GGM:0, ANR:285, ANR2:285, CCR:5, BOK:37, EE:245, NR3D:165, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Preview( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2000 )
IDX_SET( DBS:226, OBC:45, BPC:226, NR1:206, PDC:206,  UDM:226, GGM:0, ANR:286, ANR2:286, CCR:6, BOK:38, EE:246, NR3D:166, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Preview( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2400 )
IDX_SET( DBS:227, OBC:45, BPC:227, NR1:207, PDC:207,  UDM:227, GGM:0, ANR:287, ANR2:287, CCR:7, BOK:38, EE:247, NR3D:167, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Preview( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2800 )
IDX_SET( DBS:228, OBC:45, BPC:228, NR1:208, PDC:208,  UDM:228, GGM:0, ANR:288, ANR2:288, CCR:8, BOK:39, EE:248, NR3D:168, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Preview( ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_3200 )
IDX_SET( DBS:229, OBC:45, BPC:229, NR1:209, PDC:209,  UDM:229, GGM:0, ANR:289, ANR2:289, CCR:9, BOK:39, EE:249, NR3D:169, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_NORMAL)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_ACTION)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_NIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_THEATRE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_BEACH)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_SNOW)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_SUNSET)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_FIREWORKS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_SPORTS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_PARTY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_HDR)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom3, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Preview> <Sensor Mode: Custom4>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_UNSUPPORTED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Preview( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_100 )
IDX_SET( DBS:230, OBC:46, BPC:230, NR1:210, PDC:210,  UDM:230, GGM:0, ANR:290, ANR2:290, CCR:0, BOK:40, EE:250, NR3D:170, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Preview( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_200 )
IDX_SET( DBS:231, OBC:46, BPC:231, NR1:211, PDC:211,  UDM:231, GGM:0, ANR:291, ANR2:291, CCR:1, BOK:40, EE:251, NR3D:171, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Preview( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_400 )
IDX_SET( DBS:232, OBC:46, BPC:232, NR1:212, PDC:212,  UDM:232, GGM:0, ANR:292, ANR2:292, CCR:2, BOK:41, EE:252, NR3D:172, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Preview( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_800 )
IDX_SET( DBS:233, OBC:47, BPC:233, NR1:213, PDC:213,  UDM:233, GGM:0, ANR:293, ANR2:293, CCR:3, BOK:41, EE:253, NR3D:173, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Preview( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1200 )
IDX_SET( DBS:234, OBC:47, BPC:234, NR1:214, PDC:214,  UDM:234, GGM:0, ANR:294, ANR2:294, CCR:4, BOK:42, EE:254, NR3D:174, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Preview( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1600 )
IDX_SET( DBS:235, OBC:47, BPC:235, NR1:215, PDC:215,  UDM:235, GGM:0, ANR:295, ANR2:295, CCR:5, BOK:42, EE:255, NR3D:175, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Preview( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2000 )
IDX_SET( DBS:236, OBC:47, BPC:236, NR1:216, PDC:216,  UDM:236, GGM:0, ANR:296, ANR2:296, CCR:6, BOK:43, EE:256, NR3D:176, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Preview( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2400 )
IDX_SET( DBS:237, OBC:47, BPC:237, NR1:217, PDC:217,  UDM:237, GGM:0, ANR:297, ANR2:297, CCR:7, BOK:43, EE:257, NR3D:177, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Preview( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2800 )
IDX_SET( DBS:238, OBC:47, BPC:238, NR1:218, PDC:218,  UDM:238, GGM:0, ANR:298, ANR2:298, CCR:8, BOK:44, EE:258, NR3D:178, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Preview( ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_3200 )
IDX_SET( DBS:239, OBC:47, BPC:239, NR1:219, PDC:219,  UDM:239, GGM:0, ANR:299, ANR2:299, CCR:9, BOK:44, EE:259, NR3D:179, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_NORMAL)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_ACTION)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_NIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_THEATRE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_BEACH)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_SNOW)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_SUNSET)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_FIREWORKS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_SPORTS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_PARTY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_HDR)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom4, MTK_CONTROL_SCENE_MODE_BARCODE)

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// <ISP Profile: Preview> <Sensor Mode: Custom5>
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

//+++++++++++++++++++++++++++++++++++++++
//  MTK_CONTROL_SCENE_MODE_UNSUPPORTED
//+++++++++++++++++++++++++++++++++++++++
// ISO 100
IDX_MODE_Preview( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_100 )
IDX_SET( DBS:240, OBC:48, BPC:240, NR1:220, PDC:220,  UDM:240, GGM:0, ANR:300, ANR2:300, CCR:0, BOK:45, EE:260, NR3D:180, MFB:0, LCE:0);
// ISO 200
IDX_MODE_Preview( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_200 )
IDX_SET( DBS:241, OBC:48, BPC:241, NR1:221, PDC:221,  UDM:241, GGM:0, ANR:301, ANR2:301, CCR:1, BOK:45, EE:261, NR3D:181, MFB:0, LCE:0);
// ISO 400
IDX_MODE_Preview( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_400 )
IDX_SET( DBS:242, OBC:48, BPC:242, NR1:222, PDC:222,  UDM:242, GGM:0, ANR:302, ANR2:302, CCR:2, BOK:46, EE:262, NR3D:182, MFB:0, LCE:0);
// ISO 800
IDX_MODE_Preview( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_800 )
IDX_SET( DBS:243, OBC:49, BPC:243, NR1:223, PDC:223,  UDM:243, GGM:0, ANR:303, ANR2:303, CCR:3, BOK:46, EE:263, NR3D:183, MFB:0, LCE:0);
// ISO 1200
IDX_MODE_Preview( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1200 )
IDX_SET( DBS:244, OBC:49, BPC:244, NR1:224, PDC:224,  UDM:244, GGM:0, ANR:304, ANR2:304, CCR:4, BOK:47, EE:264, NR3D:184, MFB:0, LCE:0);
// ISO 1600
IDX_MODE_Preview( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_1600 )
IDX_SET( DBS:245, OBC:49, BPC:245, NR1:225, PDC:225,  UDM:245, GGM:0, ANR:305, ANR2:305, CCR:5, BOK:47, EE:265, NR3D:185, MFB:0, LCE:0);
// ISO 2000
IDX_MODE_Preview( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2000 )
IDX_SET( DBS:246, OBC:49, BPC:246, NR1:226, PDC:226,  UDM:246, GGM:0, ANR:306, ANR2:306, CCR:6, BOK:48, EE:266, NR3D:186, MFB:0, LCE:0);
// ISO 2400
IDX_MODE_Preview( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2400 )
IDX_SET( DBS:247, OBC:49, BPC:247, NR1:227, PDC:227,  UDM:247, GGM:0, ANR:307, ANR2:307, CCR:7, BOK:48, EE:267, NR3D:187, MFB:0, LCE:0);
// ISO 2800
IDX_MODE_Preview( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_2800 )
IDX_SET( DBS:248, OBC:49, BPC:248, NR1:228, PDC:228,  UDM:248, GGM:0, ANR:308, ANR2:308, CCR:8, BOK:49, EE:268, NR3D:188, MFB:0, LCE:0);
// ISO 3200
IDX_MODE_Preview( ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_UNSUPPORTED, eIDX_ISO_3200 )
IDX_SET( DBS:249, OBC:49, BPC:249, NR1:229, PDC:229,  UDM:249, GGM:0, ANR:309, ANR2:309, CCR:9, BOK:49, EE:269, NR3D:189, MFB:0, LCE:0);

//+++++++++++++++++++++++++++++++++++++++
//  Scene Mode
//+++++++++++++++++++++++++++++++++++++++
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_NORMAL)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_ACTION)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_LANDSCAPE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_NIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_NIGHT_PORTRAIT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_THEATRE)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_BEACH)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_SNOW)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_SUNSET)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_STEADYPHOTO)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_FIREWORKS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_SPORTS)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_PARTY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_CANDLELIGHT)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_HDR)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_FACE_PRIORITY)
PREVIEW_SCENE_MODE_CONFIG(ESensorMode_Custom5, MTK_CONTROL_SCENE_MODE_BARCODE)

#endif //  _CFG_ISP_TUNING_IDX_PREVIEW_H_

