#if 0
#define NVRAM_SLK_TBL_NUM                             (10  ) 
#define NVRAM_DM_TBL_NUM                              (1600)
#define NVRAM_YNR_TBL_NUM                             (1000)
#define NVRAM_YNR_LCE_LINK_TBL_NUM                    (1200
#define NVRAM_YNR_FD_TBL_NUM                          (1200)
#define NVRAM_CNR_CNR_TBL_NUM                         (2000)
#define NVRAM_EE_TBL_NUM                              (1600)
#define NVRAM_NR3D_TBL_NUM                            (1200)
#define NVRAM_HFG_TBL_NUM                             (1200)
#define NVRAM_DSDN_TBL_NUM                            (5   )
#define NVRAM_OBC_TBL_NUM                             (200 )
#define NVRAM_BPC_BPC_TBL_NUM                         (200 )
#define NVRAM_BPC_CT_TBL_NUM                          (200 )
#define NVRAM_BPC_PDC_TBL_NUM                         (200 )
#define NVRAM_LDNR_TBL_NUM                            (200 )
#define NVRAM_CNR_CCR_TBL_NUM                         (100 )
#define NVRAM_CNR_ABF_TBL_NUM                         (100 )
#define NVRAM_LPCNR_TBL_NUM                           (300 )
#define NVRAM_FUS_TBL_NUM                             (100 )
#define NVRAM_ZFUS_TBL_NUM                            (100 )
#define NVRAM_MFB_TBL_NUM                             (200 )
#define NVRAM_MIX_TBL_NUM                             (200 )
#define NVRAM_YNR_TBL_TBL_NUM                         (200 )
#define NVRAM_YNRS_TBL_NUM                            (100 )

//Feature
#define NVRAM_SWNR_TBL_NUM                (300)
#define NVRAM_SWNR_THRES_TBL_NUM          (30)
#define NVRAM_MFNR_TBL_NUM                (200)
#define NVRAM_MFNR_THRES_TBL_NUM          (10)
#define NVRAM_AINR_TBL_NUM                (100 )
#define NVRAM_CLEARZOOM_TBL_NUM           (7)
#define NVRAM_CA_LTM_TBL_NUM              (30)
#define NVRAM_HFG_TBL_NUM                 (1200)
#define NVRAM_BSS_TBL_NUM                 (200)

//tone
#define ISP_NVRAM_GMA_TBL_NUM               (60)
#define ISP_NVRAM_LCE_TBL_NUM               (60)
#define ISP_NVRAM_DCE_TBL_NUM               (60)
#define ISP_NVRAM_HLR_TBL_NUM               (60)
#define ISP_NVRAM_LTM_TBL_NUM               (60)
#endif
#define NVRAM_SLK_TBL_NUM         (10)
#define NVRAM_DM_TBL_NUM         (1600)
#define NVRAM_YNR_TBL_NUM         (2000)
#define NVRAM_YNR_LCE_LINK_TBL_NUM         (1200)
#define NVRAM_YNR_FD_TBL_NUM         (1200)
#define NVRAM_CNR_CNR_TBL_NUM         (2000)
#define NVRAM_EE_TBL_NUM         (1600)
#define NVRAM_NR3D_TBL_NUM         (1200)
#define NVRAM_HFG_TBL_NUM         (1200)
#define NVRAM_DSDN_TBL_NUM         (5)
#define NVRAM_OBC_TBL_NUM         (200)
#define NVRAM_BPC_BPC_TBL_NUM         (200)
#define NVRAM_BPC_CT_TBL_NUM         (200)
#define NVRAM_BPC_PDC_TBL_NUM         (200)
#define NVRAM_LDNR_TBL_NUM         (200)
#define NVRAM_CNR_CCR_TBL_NUM         (100)
#define NVRAM_CNR_ABF_TBL_NUM         (100)
#define NVRAM_SWNR_THRES_TBL_NUM         (30)
#define NVRAM_SWNR_TBL_NUM         (300)
#define NVRAM_LPCNR_TBL_NUM         (300)
#define NVRAM_FUS_TBL_NUM         (100)
#define NVRAM_ZFUS_TBL_NUM         (100)
#define NVRAM_MFNR_THRES_TBL_NUM         (10)
#define NVRAM_MFNR_TBL_NUM         (200)
#define NVRAM_BSS_TBL_NUM         (200)
#define NVRAM_MFB_TBL_NUM         (200)
#define NVRAM_MIX_TBL_NUM         (200)
#define NVRAM_AINR_TBL_NUM         (100)
#define NVRAM_YNR_TBL_TBL_NUM         (200)
#define NVRAM_CA_LTM_TBL_NUM         (30)
#define NVRAM_ClearZoom_TBL_NUM         (7)
#define NVRAM_YNRS_TBL_NUM         (100)
#define NVRAM_CCM_TBL_NUM                             (96  )
#define NVRAM_COLOR_PARAM_TBL_NUM                     (16  )
#define NVRAM_COLOR_TBL_NUM                           (960 )
#define NVRAM_AINR_THRES_TBL_NUM            (30)
//ToneMap
#define ISP_NVRAM_GMA_TBL_NUM               (60)
#define ISP_NVRAM_LCE_TBL_NUM               (60)
#define ISP_NVRAM_DCE_TBL_NUM               (60)
#define ISP_NVRAM_HLR_TBL_NUM               (60)
#define ISP_NVRAM_LTM_TBL_NUM               (60)

//3A
#define AF_CAM_SCENARIO_NUM_2             (10)
#define AE_CAM_SCENARIO_NUM             (20)
#define AWB_CAM_SCENARIO_NUM            (10)


